---
- name: Create /usr/local/share/skel
  file:
    path: /usr/local/share/skel
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: Install dotfiles in /usr/local/share/skel
  copy:
    src: ../ansible/dotfiles/dot.{{ item }}
    dest: /usr/local/share/skel/dot.{{ item }}
    owner: root
    group: wheel
    mode: "0644"
  with_items:
    - cshrc
    - inputrc
    - kermrc
    - login
    - login_conf
    - mail_aliases
    - mailrc
    - profile
    - shrc
    - vimrc
    - zshrc

- name: Set dotfile_list
  set_fact:
    dotfile_list: "{{ dotfile_list | default([]) + [item] }}"
  with_items:
    - inputrc
    - kermrc
    - login
    - login_conf
    - mail_aliases
    - mailrc
    - vimrc
    - zshrc

- name: Install dotfiles for root
  copy:
    src: ../ansible/dotfiles/dot.{{ item }}
    dest: /root/.{{ item }}
    owner: root
    group: wheel
    mode: "0644"
  with_items: "{{ dotfile_list }}"

- name: Check if ec2-user exists
  command: pw usershow ec2-user
  register: ec2_user_exists
  ignore_errors: true
  when: platform_is_aws

- name: Install dotfiles for ec2-user
  copy:
    src: ../ansible/dotfiles/dot.{{ item }}
    dest: /home/ec2-user/.{{ item }}
    owner: ec2-user
    group: ec2-user
    mode: "0644"
  with_items: "{{ dotfile_list }}"
  when: platform_is_aws and ec2_user_exists is defined and ec2_user_exists.rc == 0

- name: Set zsh shell for ec2-user
  user:
    name: ec2-user
    shell: /usr/local/bin/zsh
  when: platform_is_aws and ec2_user_exists is defined and ec2_user_exists.rc == 0
