---
- name: "dotfiles: create /usr/local/share/skel"
  file:
    path: /usr/local/share/skel
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: "dotfiles: install dotfiles in /usr/local/share/skel"
  copy:
    src: ../ansible/dotfiles/dot.{{ item }}
    dest: /usr/local/share/skel/dot.{{ item }}
    owner: root
    group: wheel
    mode: "0644"
  with_items:
    - cshrc
    - inputrc
    - kermrc
    - login
    - login_conf
    - mail_aliases
    - mailrc
    - profile
    - shrc
    - vimrc
    - zshrc

- name: "dotfiles: install dotfiles in /root"
  copy:
    src: ../ansible/dotfiles/dot.{{ item }}
    dest: /root/.{{ item }}
    owner: root
    group: wheel
    mode: "0644"
  with_items:
    - inputrc
    - kermrc
    - login
    - login_conf
    - mail_aliases
    - mailrc
    - vimrc
    - zshrc
    # - cshrc
    # - profile
    # - shrc
