---
- name: "ftp: add FTP group"
  lineinfile:
    dest: /etc/group
    line: "ftp:*:14:"
    regexp: "^ftp:"
    insertafter: "^games:"
  notify: pwd_mkdb

- name: "ftp: add FTP user (master.passwd)"
  lineinfile:
    dest: /etc/master.passwd
    line: ftp:*:14:14::0:0:Anonymous FTP Admin:/var/ftp:/sbin/nologin
    regexp: "^ftp:"
    insertafter: "^man:"
  notify: pwd_mkdb

- name: "ftp: add FTP user (ftpusers)"
  lineinfile:
    dest: /etc/ftpusers
    line: ftp
    regexp: ^ftp$
    insertafter: ^man$

# Workaround for "pw: user '...' disappeared during update"
- name: "ftp: flush handlers"
  meta: flush_handlers

- name: "ftp: create /var/ftp"
  file:
    path: /var/ftp
    state: directory
    owner: ftp
    group: ftp
    mode: "0755"
