---
rc_conf: {}
periodic_conf:
  daily_output: /var/log/daily.log
  weekly_output: /var/log/weekly.log
  monthly_output: /var/log/monthly.log
  daily_status_security_output: /var/log/security-daily.log
  weekly_status_security_output: /var/log/security-weekly.log
  monthly_status_security_output: /var/log/security-monthly.log
  daily_status_security_enable: "NO"
  weekly_status_security_enable: "NO"
  monthly_status_security_enable: "NO"
  daily_clean_tmps_enable: "YES"
  daily_status_zfs_enable: "NO"
  daily_scrub_zfs_enable: "NO"
  daily_scrub_zfs_default_threshold: "0"

pw_conf:
  skeleton: /usr/local/share/skel

bsdkit_provision:
  update_dns: true
