---
- hosts: all
  user: root
  gather_facts: False
  tasks:
    - name: "Bootstrap pkgng"
      raw: /bin/sh -c /usr/bin/env ASSUME_ALWAYS_YES=yes pkg -N || pkg update -f
      changed_when: False

    - name: "Install Python"
      raw: /usr/bin/env http_proxy="{{ lookup('env', 'BSDKIT_JAIL_PROXY') }}"
        pkg install -y python
      changed_when: False

- hosts: all
  user: root
  tasks:
    - name: "Include kenv.inc.yml"
      include: include/kenv.inc.yml

    - name: "Include facts.inc.yml"
      include: include/facts.inc.yml

    - name: "Include zpool.inc.yml"
      include: include/zpool.inc.yml

    - name: "Touch rc.conf (exec)"
      file:
        path: /etc/rc.conf
        state: touch

    - name: "Include remove.inc.yml"
      include: include/remove.inc.yml

    - name: "Create /usr/local/etc"
      file:
        path: /usr/local/etc
        state: directory
        owner: root
        group: wheel
        mode: "0755"

    - name: "Include login-conf.inc.yml"
      include: include/login-conf.inc.yml

    - name: "Include pkg.inc.yml"
      include: include/pkg.inc.yml

    - name: "Include kernconf.inc.yml"
      include: include/kernconf.inc.yml

    - name: "Digital Ocean"
      include: include/digitalocean.inc.yml

    - name: "Include runit.inc.yml"
      include: include/runit.inc.yml

    - name: "Install configuration files in /etc"
      copy:
        src: ../ansible/{{ item }}
        dest: /etc/{{ item }}
        owner: root
        group: wheel
        mode: "0644"
      with_items:
        - csh.cshrc
        - make.conf
        - src.conf

    - name: "Include periodic.inc.yml"
      include: include/periodic.inc.yml

    - name: "Block: host"
      when: bsdkit_install_host
      block:
        - name: "Include zfs.inc.yml"
          include: include/zfs.inc.yml

        - name: "Include loader.inc.yml"
          include: include/loader.inc.yml

        - name: "Include bsdenv.inc.yml"
          include: include/bsdenv.inc.yml

        - name: "Include postgres-zfs.inc.yml"
          include: include/postgres-zfs.inc.yml

        - name: "Include mysql-zfs.inc.yml"
          include: include/mysql-zfs.inc.yml

        - name: "Install sysctl.conf"
          copy:
            src: ../ansible/{{ item }}
            dest: /etc/{{ item }}
            owner: root
            group: wheel
            mode: "0644"
            backup: True
          with_items:
            - sysctl.conf

        - name: "Install /etc/defaults/vendor.conf (host version)"
          copy:
            src: ../ansible/vendor.conf
            dest: /etc/defaults/vendor.conf
            owner: root
            group: wheel
            mode: "0644"

        - name: "Configure /etc/devfs.conf"
          lineinfile:
            dest: /etc/devfs.conf
            regexp: "^{{ item }}"
            state: absent
          with_items:
            - ".*devstat"
            - ".*fuse.*"

        - name: "Set http_proxy in pkg.conf"
          lineinfile:
            dest: /usr/local/etc/pkg.conf
            line: 'pkg_env: { http_proxy: "{{ bsdkit_jail_proxy }}" }'
            regexp: ^pkg_env
            insertafter: EOF
          when: bsdkit_jail_proxy | length > 0

        - name: "Install /usr/local/etc/smartd.conf"
          copy:
            src: ../ansible/smartd.conf
            dest: /usr/local/etc/smartd.conf
            owner: root
            group: wheel
            mode: "0644"

        - name: "Install base packages (host)"
          pkgng:
            name:
              - beadm
              - smartmontools
            state: present

    - name: "Block: jail"
      when: not bsdkit_install_host
      block:
        - name: "Install /etc/defaults/vendor.conf (jail version)"
          copy:
            src: ../ansible/vendor.conf.jail
            dest: /etc/defaults/vendor.conf
            owner: root
            group: wheel
            mode: "0644"

    - name: "Remove obsolete /usr/local/etc/portmaster.rc"
      file:
        path: /usr/local/etc/portmaster.rc
        state: absent

    - name: "Include dotfiles.inc.yml"
      include: include/dotfiles.inc.yml

    - name: "Include sudo.inc.yml"
      include: include/sudo.inc.yml

    - name: "Include vagrant.inc.yml"
      include: include/vagrant.inc.yml

    - name: "Include newsyslog.inc.yml"
      include: include/newsyslog.inc.yml

    - name: "Include ssh.inc.yml"
      include: include/ssh.inc.yml

    - name: "Include zoneinfo.inc.yml"
      include: include/zoneinfo.inc.yml

    - name: "Include crontab.inc.yml"
      include: include/crontab.inc.yml

    - name: "Include syslog.inc.yml"
      include: include/syslog.inc.yml

    - name: "Include ftp.inc.yml"
      include: include/ftp.inc.yml

    - name: "Include postgres.inc.yml"
      include: include/postgres.inc.yml

    - name: "Include mysql.inc.yml"
      include: include/mysql.inc.yml

    - name: "Install base packages (common)"
      pkgng:
        name:
          - align
          - bash
          - ca_root_nss
          - cpdup
          - curl
          - direnv
          - fzf
          - gnu-watch
          - htop
          - jq
          - lftp
          - ncdu
          - pv
          - rsync
          - socat
          - sudo
          - the_silver_searcher
          - tmux
          - ts
          - vim
          - zsh
        state: present

    # - name: "Include ca-root-nss.inc.yml"
    #   include: include/ca-root-nss.inc.yml

    - name: "Include virtualbox.inc.yml"
      include: include/virtualbox.inc.yml

    - name: "Include vmware.inc.yml"
      include: include/vmware.inc.yml

    - name: "Include cleanup.inc.yml"
      include: include/cleanup.inc.yml

  handlers:
    - name: cap_mkdb
      command:
        cmd: cap_mkdb /etc/login.conf

    - name: pwd_mkdb
      command:
        cmd: pwd_mkdb -p /etc/master.passwd
