---
- hosts: all
  user: root
  gather_facts: no
  tasks:
    - name: "Bootstrap pkgng"
      raw: "/bin/sh -c /usr/bin/env ASSUME_ALWAYS_YES=yes pkg -N || pkg update -f"
      changed_when: no

    - name: "Install Python"
      raw: "/usr/bin/env http_proxy=\"{{ lookup('env', 'BSDKIT_JAIL_PROXY') }}\" pkg install -y lang/python"
      changed_when: no

- hosts: all
  user: root
  tasks:
    - name: "Include facts.inc.yml"
      tags: always
      include: include/facts.inc.yml

    - name: "Set root shell"
      tags:
        - configure
      user:
        name: root
        shell: /bin/sh

    - name: "Touch files"
      file:
        path: "{{ item }}"
        state: touch
        mode: "0644"
      changed_when: no
      loop:
        - /boot/loader.conf
        - /etc/rc.conf
        - /etc/rc.conf.local
        - /etc/sysctl.conf
        - /etc/sysctl.conf.local

    - name: "Include remove.inc.yml"
      tags:
        - configure
        - include-remove
      include: include/remove.inc.yml

    - name: "Create /usr/local/etc"
      tags:
        - configure
      file:
        path: /usr/local/etc
        state: directory
        owner: root
        group: wheel
        mode: "0755"

    # - name: "Include login-conf.inc.yml"
    #   include: include/login-conf.inc.yml

    - name: "Include pkg.inc.yml"
      include: include/pkg.inc.yml

    - name: "Include kernconf.inc.yml"
      tags:
        - configure
        - include-kernconf
      include: include/kernconf.inc.yml

    - name: "Digital Ocean"
      tags: digitalocean
      include: include/digitalocean.inc.yml
      when: platform_is_digitalocean | bool

    - name: "Include runit.inc.yml"
      tags:
        - configure
        - include-runit
      include: include/runit.inc.yml

    - name: "Install configuration files in /etc"
      tags:
        - configure
      copy:
        src: ../ansible/{{ item }}
        dest: /etc/{{ item }}
        owner: root
        group: wheel
        mode: "0644"
      with_items:
        - csh.cshrc
        - make.conf
        - src.conf

    - name: "Include periodic.inc.yml"
      tags:
        - configure
        - include-periodic
      include: include/periodic.inc.yml

    - name: "Block: host"
      when: is_host_install
      block:
        - name: "Include zfs.inc.yml"
          include: include/zfs.inc.yml
          when: not is_chroot_install

        - name: "Include loader.inc.yml"
          include: include/loader.inc.yml

        - name: "Include bsdenv.inc.yml"
          include: include/bsdenv.inc.yml

        - name: "Include postgres-zfs.inc.yml"
          include: include/postgres-zfs.inc.yml
          when: not is_chroot_install

        - name: "Include mysql-zfs.inc.yml"
          include: include/mysql-zfs.inc.yml
          when: not is_chroot_install

        - name: "Install sysctl.conf"
          copy:
            src: ../ansible/{{ item }}
            dest: /etc/{{ item }}
            owner: root
            group: wheel
            mode: "0644"
          with_items:
            - sysctl.conf

        - name: "Install /etc/defaults/vendor.conf (host version)"
          copy:
            src: ../ansible/vendor.conf
            dest: /etc/defaults/vendor.conf
            owner: root
            group: wheel
            mode: "0644"

        - name: "Configure /etc/devfs.conf"
          lineinfile:
            dest: /etc/devfs.conf
            regexp: "^{{ item }}"
            state: absent
          with_items:
            - ".*devstat"
            - ".*fuse.*"

        - name: "Set http_proxy in pkg.conf"
          lineinfile:
            dest: /usr/local/etc/pkg.conf
            line: 'pkg_env: { http_proxy: "{{ bsdkit_jail_proxy }}" }'
            regexp: ^pkg_env
            insertafter: EOF
          when: bsdkit_jail_proxy | length > 0

        - name: "Install /usr/local/etc/smartd.conf"
          copy:
            src: ../ansible/smartd.conf
            dest: /usr/local/etc/smartd.conf
            owner: root
            group: wheel
            mode: "0644"

        - name: "Install base packages (host)"
          pkgng:
            name:
              - sysutils/beadm
              - sysutils/smartmontools
            state: present

    - name: "Block: jail"
      when: is_jail_install
      block:
        - name: "Install /etc/defaults/vendor.conf (jail version)"
          copy:
            src: ../ansible/vendor.conf.jail
            dest: /etc/defaults/vendor.conf
            owner: root
            group: wheel
            mode: "0644"

    - name: "Remove obsolete /usr/local/etc/portmaster.rc"
      file:
        path: /usr/local/etc/portmaster.rc
        state: absent

    - name: "Include dotfiles.inc.yml"
      tags:
        - configure
        - include-dotfiles
      include: include/dotfiles.inc.yml

    - name: "Include sudo.inc.yml"
      tags:
        - configure
        - include-sudo
      include: include/sudo.inc.yml

    - name: "Include vagrant.inc.yml"
      include: include/vagrant.inc.yml

    - name: "Include spiped.inc.yml"
      tags:
        - configure
        - include-spiped
      include: include/spiped.inc.yml

    - name: "Include newsyslog.inc.yml"
      tags:
        - configure
        - include-newsyslog
      include: include/newsyslog.inc.yml

    - name: "Include ssh.inc.yml"
      tags:
        - configure
        - include-ssh
      include: include/ssh.inc.yml

    - name: "Include fscd.inc.yml"
      tags:
        - configure
        - include-fscd
      include: include/fscd.inc.yml

    - name: "Include zoneinfo.inc.yml"
      tags:
        - configure
        - include-zoneinfo
      include: include/zoneinfo.inc.yml

    - name: "Include crontab.inc.yml"
      tags:
        - configure
        - include-crontab
      include: include/crontab.inc.yml

    - name: "Include syslog.inc.yml"
      tags:
        - configure
        - include-syslog
      include: include/syslog.inc.yml

    - name: "Include ftp.inc.yml"
      tags:
        - configure
        - include-ftp
      include: include/ftp.inc.yml

    - name: "Include postgres.inc.yml"
      include: include/postgres.inc.yml

    - name: "Include mysql.inc.yml"
      include: include/mysql.inc.yml

    - name: "Install base packages (common)"
      tags:
        - configure
      pkgng:
        name:
          - archivers/zip
          - devel/git
          - editors/bvi
          - editors/nano
          - editors/vim
          - ftp/curl
          - ftp/lftp
          - misc/buffer
          - misc/gnu-watch
          - misc/inplace
          - misc/mbuffer
          - misc/mc
          - net/croc
          - net/rsync
          - net/socat
          - security/ca_root_nss
          - security/doas
          - security/gnupg
          - shells/bash
          - shells/zsh
          - sysutils/ansible
          - sysutils/checkrestart
          - sysutils/clone
          - sysutils/cpdup
          - sysutils/direnv
          - sysutils/fsc
          - sysutils/htop
          - sysutils/lsblk
          - sysutils/ncdu
          - sysutils/pv
          - sysutils/renameutils
          - sysutils/runit
          - sysutils/smenu
          - sysutils/spiped
          - sysutils/tmux
          - sysutils/ts
          - textproc/align
          - textproc/fzf
          - textproc/jq
          - textproc/the_silver_searcher
        state: present

    # - name: "Include ca-root-nss.inc.yml"
    #   include: include/ca-root-nss.inc.yml

    - name: "Include virtualbox.inc.yml"
      include: include/virtualbox.inc.yml
      when: platform_is_virtualbox | bool

    - name: "Include vmware.inc.yml"
      include: include/vmware.inc.yml
      when: platform_is_vmware | bool

    - name: "Include cleanup.inc.yml"
      include: include/cleanup.inc.yml

  handlers:
    - name: cap_mkdb
      command:
        cmd: cap_mkdb /etc/login.conf

    - name: pwd_mkdb
      command:
        cmd: pwd_mkdb -p /etc/master.passwd

    - name: restart_syslogd
      service:
        name: syslogd
        state: restarted

    - name: restart_cron
      service:
        name: cron
        state: restarted

    - name: restart_fscd
      service:
        name: fscd
        state: restarted

    - name: restart_sshd
      service:
        name: sshd
        state: restarted
