---
- hosts: jail
  user: root
  gather_facts: no
  tasks:
    - raw: pkg install -y python

- hosts: jail
  user: root
  tasks:
    - set_fact: freebsd_release=11
      when: ansible_distribution_release[:3] == "11."

    - set_fact: freebsd_release=10
      when: ansible_distribution_release[:3] == "10."

    - set_fact: ssh_public_key="{{lookup('env','SSH_PUBLIC_KEY')}}"

    - stat: path=/boot/kernel/kernel
      register: stat_kernel

    - stat: path=/usr/src/sys
      register: stat_sys

    - authorized_key: user=root key="{{ssh_public_key}}"
      when: ssh_public_key != ""

    - file: >
        path=/usr/local/etc state=directory
        owner=root group=wheel mode=755

    - file: >
        path=/usr/local/etc/sv state=directory
        owner=root group=wheel mode=755

    - file: >
        path=/var/service state=directory
        owner=root group=wheel mode=755

    - file: >
        path=/service src=var/service state=link
        owner=root group=wheel mode=755

    - copy: >
        src=../ansible/RELENG_{{freebsd_release}}.{{ansible_architecture}}
        dest=/usr/src/sys/{{ansible_architecture}}/conf/KERNEL
        owner=root group=wheel mode=644
      when: stat_sys.stat.exists

    - copy: >
        src=../ansible/DEBUG dest=/usr/src/sys/{{ansible_architecture}}/conf/DEBUG
        owner=root group=wheel mode=644
      when: stat_sys.stat.exists

    - command: sysrc -n zfs_enable
      register: sysrc_zfs_enable

    - copy: >
        src=../ansible/{{item}} dest=/etc/{{item}}
        owner=root group=wheel mode=644
      with_items:
        - csh.cshrc
        - make.conf
        - mergemaster.rc
        - periodic.conf
        - rc.conf
        - src.conf

    - command: sysrc zfs_enable="{{sysrc_zfs_enable.stdout}}"
      when: sysrc_zfs_enable|success

    - copy: >
        src=../ansible/{{item}} dest=/etc/{{item}}
        owner=root group=wheel mode=644
      with_items:
        - sysctl.conf
      when: stat_kernel.stat.exists

    - copy: >
        src=../ansible/{{item}} dest=/boot/{{item}}
        owner=root group=wheel mode=644
      with_items:
        - loader.conf
      when: stat_kernel.stat.exists

    - copy: >
        src=../ansible/dot.{{item}} dest=/usr/share/skel/dot.{{item}}
        owner=root group=wheel mode=644
      with_items:
        - kermrc
        - inputrc
        - zshrc

    - copy: >
        src=../ansible/dot.{{item}} dest=/root/.{{item}}
        owner=root group=wheel mode=644
      with_items:
        - kermrc
        - inputrc
        - zshrc

    - copy: >
        src=../ansible/sudoers dest=/usr/local/etc/sudoers
        owner=root group=wheel mode=440

    - file: >
        path=/etc/newsyslog.conf.d/ state=directory
        owner=root group=wheel mode=755

    - copy: >
        src=../ansible/newsyslog.conf dest=/etc/newsyslog.conf.d/newsyslog.conf
        owner=root group=wheel mode=644

    - copy: >
        src=../ansible/firewall dest=/etc/firewall
        owner=root group=wheel mode=644
      when: stat_kernel.stat.exists

    - copy: >
        src=../ansible/smartd.conf dest=/usr/local/etc/smartd.conf
        owner=root group=wheel mode=644
      when: stat_kernel.stat.exists

    - copy: >
        src=../ansible/portmaster.rc dest=/usr/local/etc/portmaster.rc
        owner=root group=wheel mode=644

    - lineinfile: >
        dest=/etc/ssh/sshd_config
        line="UseDNS no"
        regexp="^UseDNS"
        insertafter=EOF

    - lineinfile: >
        dest=/etc/ssh/sshd_config
        line="PermitRootLogin without-password"
        regexp="^PermitRootLogin"
        insertafter=EOF

    - lineinfile: >
        dest=/etc/devfs.conf
        regexp="^{{item}}"
        state=absent
      with_items:
        - ".*devstat"
        - ".*fuse.*"
      when: stat_kernel.stat.exists

    - stat: path=/var/db/zoneinfo
      register: stat_zoneinfo

    - command: tzsetup Europe/Rome
      when: not stat_zoneinfo.stat.exists

    - lineinfile: >
        dest=/etc/crontab
        line="MAILTO=\"\""
        regexp="^MAILTO"
        insertafter="^SHELL="

    - lineinfile: >
        dest=/etc/syslog.conf
        regexp="/dev/console$"
        state=absent

    - file: >
        path=/var/ftp state=directory
        owner=root group=wheel mode=755

    - lineinfile: >
        dest=/etc/master.passwd
        line="ftp:*:14:14::0:0:Anonymous FTP Admin:/var/ftp:/nonexistent"
        regexp="^ftp:"
        insertafter="^man:"
      notify: pwd_mkdb

    - file: >
        path=/etc/ssl/certs state=directory
        owner=root group=wheel mode=755

    - pkgng: name={{item}} state=present
      with_items:
        - ca_root_nss
        - rsync
        - sudo
        - tmux
        - vim
        - zsh

    - stat: path=/usr/local/share/certs/ca-root-nss.crt
      register: stat_ca_root_nss

    - copy: >
        src=/usr/local/share/certs/ca-root-nss.crt
        dest=/etc/ssl/cert.pem
        owner=root group=wheel mode=644
      when: stat_ca_root_nss.stat.exists

    - command: pkg clean -a -y
      changed_when: false

  handlers:
    - name: pwd_mkdb
      command: pwd_mkdb /etc/master.passwd

- include: virt.yml

- hosts: jail
  user: root
  gather_facts: no
  tasks:
    - authorized_key: user=root key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDUde1HTbCcpmEsgtFUJZKYmrIxK+MMAAZEr0lCY1KRZOIxG75561r78kxHprU9144rMtp/2GjJJjfDoIweXh+YKnRKVj3ADPw5WHS93dJVK5vHGGv+fF1tdXlbyO29gQwwqrWbPmqvshbc9F2AOPWHmV0CuqYpZ6Sk0EzvBCVmx52uZE9Nbr19dBBk885xWVNH4U4NHuEYUhbxgcaaCtGjsJy/+wgUqCTJp6xavB73Pf207yI8ZnMzfaje0EMN2vDrupntDon3lgtpc2VFntF1DQwn0BSGD1IW1xyokdbEIPt2hCt03cbi3G/7Pl7oaVZLfctNYE7j9ooruZEZ/ovN bsdkit" state=absent
