---
- hosts: jail
  user: root
  gather_facts: no
  tasks:
    - name: "sysctl security.jail.jailed"
      command: sysctl -n security.jail.jailed
      register: security_jail_jailed

    - name: "kenv smbios.system.product"
      shell: kenv smbios.system.product || true
      register: system_product

    - name: "kenv smbios.bios.vendor"
      shell: kenv smbios.bios.vendor || true
      register: bios_vendor

    - name: "VirtualBox configuration"
      lineinfile: >
        dest=/etc/rc.conf
        line="{{item}}_enable=\"YES\""
        regexp="^{{item}}_enable"
        insertafter=EOF
      with_items:
        - vboxguest
        - vboxservice
      when: system_product.stdout == "VirtualBox" and security_jail_jailed.stdout == "0"

    - name: "VMware configuration"
      lineinfile: >
        dest=/etc/rc.conf
        line="{{item}}_enable=\"YES\""
        regexp="^{{item}}_enable"
        insertafter=EOF
      with_items:
        - vmware_guest_vmblock
        - vmware_guest_vmhgfs
        - vmware_guest_vmmemctl
        - vmware_guest_vmxnet
        - vmware_guestd
      when: system_product.stdout == "VMware Virtual Platform" and security_jail_jailed.stdout == "0"

# smbios.bios.vendor="BHYVE"
