---
- hosts: all
  user: root
  gather_facts: false
  tasks:
    - name: "kenv smbios.system.product"
      command: "kenv smbios.system.product"
      changed_when: false
      ignore_errors: true
      register: system_product

    - name: "kenv smbios.bios.vendor"
      command: "kenv smbios.bios.vendor"
      changed_when: false
      ignore_errors: true
      register: bios_vendor

    - name: "VirtualBox configuration"
      lineinfile:
        dest: /etc/rc.conf
        line: "{{ item }}_enable=\"YES\""
        regexp: "^{{ item }}_enable"
        insertafter: EOF
      with_items:
        - vboxguest
        - vboxservice
      when: system_product.stdout == "VirtualBox"

    - name: "VMware configuration"
      lineinfile:
        dest: /etc/rc.conf
        line: "{{ item }}_enable=\"YES\""
        regexp: "^{{ item }}_enable"
        insertafter: EOF
      with_items:
        - vmware_guest_vmblock
        - vmware_guest_vmhgfs
        - vmware_guest_vmmemctl
        - vmware_guest_vmxnet
        - vmware_guestd
      when: system_product.stdout == "VMware Virtual Platform"

# smbios.bios.vendor="BHYVE"
# smbios.bios.vendor="Amazon EC2"
# smbios.bios.vendor="Google"
# smbios.system.product="Google Compute Engine"
