#!/bin/sh

# c7563ecc-b82d-4632-8e95-946223a55dce

set -o errexit -o nounset -o pipefail

exec 2>&1

[ -f config ] && . $(realpath config)

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi


: ${REDIS_USER:="redis"}
: ${REDIS_GROUP:="redis"}
: ${REDIS_ARGS="redis.conf"}
: ${REDIS_PORT=""}

mkdir -p data

chown -R ${REDIS_USER}:${REDIS_GROUP} data

if [ -n "${REDIS_PORT}" ]; then
    REDIS_ARGS="--port ${REDIS_PORT} ${REDIS_ARGS}"
fi

if [ -n "${ENVRC}" ]; then
    exec env -S "${ENVRC}" chpst -u ${REDIS_USER}:${REDIS_GROUP} ${CHPST_ARGS} /usr/local/bin/redis-server ${REDIS_ARGS}
else
    exec chpst -u ${REDIS_USER}:${REDIS_GROUP} ${CHPST_ARGS} /usr/local/bin/redis-server ${REDIS_ARGS}
fi
