#!/bin/sh

# C7563ECC-B82D-4632-8E95-946223A55DCE

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . $(realpath config)

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi

ENV_ARGS=""
if [ -n "${ENVRC}" ]; then
    ENV_ARGS="-S \"${ENVRC}\""
fi

: ${REDIS_USER:="redis"}
: ${REDIS_GROUP:="redis"}
: ${REDIS_ARGS="redis.conf"}
: ${REDIS_PORT=""}

mkdir -p data

chown -R ${REDIS_USER}:${REDIS_GROUP} data

if [ -n "${REDIS_PORT}" ]; then
    REDIS_ARGS="--port ${REDIS_PORT} ${REDIS_ARGS}"
fi

exec env ${ENV_ARGS} chpst -u ${REDIS_USER}:${REDIS_GROUP} ${CHPST_ARGS} /usr/local/bin/redis-server ${REDIS_ARGS}
