#!/bin/sh

# 6e3b9cfa-bc36-403d-9914-536fea3a9778

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/*)"
fi

: ${BENTHOS_DATA_DIR:="/var/db/benthos"}
: ${BENTHOS_USER:="benthos"}
: ${BENTHOS_GROUP:="benthos"}
: ${BENTHOS_ARGS="-c benthos.yml"}
: ${BENTHOS_CERT_FILE:=""} # /usr/local/etc/letsencrypt/live/FQDN/fullchain.pem
: ${BENTHOS_KEY_FILE:=""}  # /usr/local/etc/letsencrypt/live/FQDN/privkey.pem

if [ -n "${BENTHOS_CERT_FILE}" ] && ! echo "${BENTHOS_CERT_FILE}" | grep -q "/" > /dev/null; then
    BENTHOS_CERT_FILE="/usr/local/etc/letsencrypt/live/${BENTHOS_CERT_FILE}/fullchain.pem"
fi

if [ -n "${BENTHOS_KEY_FILE}" ] && ! echo "${BENTHOS_KEY_FILE}" | grep -q "/" > /dev/null; then
    BENTHOS_KEY_FILE="/usr/local/etc/letsencrypt/live/${BENTHOS_KEY_FILE}/privkey.pem"
fi

mkdir -p ${BENTHOS_DATA_DIR}/certs

BENTHOS_CERTS_DIR="${BENTHOS_DATA_DIR}/certs"

chown -R ${BENTHOS_USER}:${BENTHOS_GROUP} ${BENTHOS_DATA_DIR}

if [ -n "${BENTHOS_CERT_FILE}" ]; then
    install -m 644 -o benthos -g benthos "${BENTHOS_CERT_FILE}" "${BENTHOS_CERTS_DIR}/cert.pem"
fi

if [ -n "${BENTHOS_KEY_FILE}" ]; then
    install -m 600 -o benthos -g benthos "${BENTHOS_KEY_FILE}" "${BENTHOS_CERTS_DIR}/key.pem"
fi

exec env -S "${ENVRC}" chpst -u ${BENTHOS_USER}:${BENTHOS_GROUP} ${CHPST_ARGS} /usr/local/bin/benthos ${BENTHOS_ARGS}
