#!/bin/sh

# C7563ECC-B82D-4632-8E95-946223A55DCE

set -e -u

exec 2>&1

[ -f config ] && . $(realpath config)

: ${CHPST_FLAGS=""}

if [ -d env ]; then
    CHPST_FLAGS="${CHPST_FLAGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

: ${REDIS_USER:="redis"}
: ${REDIS_FLAGS="redis.conf"}

mkdir -p data

chown ${REDIS_USER}:${REDIS_USER} data

exec env -S "${ENVRC}" chpst -u ${REDIS_USER} ${CHPST_FLAGS} /usr/local/bin/redis-server ${REDIS_FLAGS}
