#!/bin/sh

# ID: 0e60835e-64b2-40c8-8865-3b5601eac028

set -o errexit -o nounset -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(grep -Ev '^\s*(#|$)' envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(grep -Ev '^\s*(#|$)' envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/* | grep -Ev '^\s*(#|$)')"
fi


# UVICORN_ARGS:
#   --root-path=/api
#   --uds /var/run/service.sock

: ${UVICORN_USER:="nobody"}
: ${UVICORN_PATH:="/tmp"}
: ${UVICORN_ARGS=""}
: ${UVICORN_APP:="app:app"}
: ${UVICORN_VENV:="${UVICORN_PATH}/.venv"}
: ${UVICORN_PYTHON:="python3"}
: ${UVICORN_PYTHON_FLAGS=""}
: ${UVICORN_UV:=""}

cd ${UVICORN_PATH}

export OSTYPE=freebsd

if [ "$(id -u)" = "0" ]; then
    CHPST_COMMAND="chpst -u ${UVICORN_USER} ${CHPST_ARGS}"
fi

PYTHON_PREFIX=""
if [ -n "${UVICORN_UV}" ]; then
    PYTHON_PREFIX="uv run "
else
    . ${UVICORN_VENV}/bin/activate
fi

if [ -n "${ENVRC}" ]; then
    exec env -S "${ENVRC}" ${CHPST_COMMAND} ${PYTHON_PREFIX}${UVICORN_PYTHON} ${UVICORN_PYTHON_FLAGS} -m uvicorn ${UVICORN_ARGS} ${UVICORN_APP}
else
    exec ${CHPST_COMMAND} ${PYTHON_PREFIX}${UVICORN_PYTHON} ${UVICORN_PYTHON_FLAGS} -m uvicorn ${UVICORN_ARGS} ${UVICORN_APP}
fi
