#!/bin/sh

# 0E60835E-64B2-40C8-8865-3B5601EAC028

set -e -u

exec 2>&1

[ -f config ] && . $(realpath config)

: ${CHPST_FLAGS:=""}

if [ -d env ]; then
    CHPST_FLAGS="${CHPST_FLAGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

: ${UVICORN_USER:="nobody"}
: ${UVICORN_PATH:="/tmp"}
: ${UVICORN_FLAGS:=""}
: ${UVICORN_APP:="app:app"}
: ${UVICORN_VENV:="${UVICORN_PATH}/.venv"}

cd ${UVICORN_PATH}

. ${UVICORN_VENV}/bin/activate

exec env -S "${ENVRC}" chpst -u ${UVICORN_USER} ${CHPST_FLAGS} uvicorn ${UVICORN_FLAGS} ${UVICORN_APP}
