#!/bin/sh

# 0e60835e-64b2-40c8-8865-3b5601eac028

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/*)"
fi

# UVICORN_ARGS:
#   --root-path=/api
#   --uds /var/run/service.sock

: ${UVICORN_USER:="nobody"}
: ${UVICORN_PATH:="/tmp"}
: ${UVICORN_ARGS=""}
: ${UVICORN_APP:="app:app"}
: ${UVICORN_VENV:="${UVICORN_PATH}/.venv"}
: ${UVICORN_PYTHON:="python3"}
: ${UVICORN_PYTHON_FLAGS=""}
: ${UVICORN_UV:=""}

cd ${UVICORN_PATH}

. ${UVICORN_VENV}/bin/activate

if [ "$(id -u)" = "0" ]; then
    CHPST_COMMAND="chpst -u ${UVICORN_USER} ${CHPST_ARGS}"
fi

PYTHON_PREFIX=""
if [ -n "${UVICORN_UV}" ]; then
    PYTHON_PREFIX="uv run "
fi

exec env -S "${ENVRC}" ${CHPST_COMMAND} ${PYTHON_PREFIX}${UVICORN_PYTHON} ${UVICORN_PYTHON_FLAGS} -m uvicorn ${UVICORN_ARGS} ${UVICORN_APP}
