#!/bin/sh

set -e -u

SCRIPT_PATH="$(dirname $(realpath $0))"
SCRIPT_NAME="$(basename $0)"

error() {
    echo "${SCRIPT_NAME}: $@"
    exit 1
}

if [ $(whoami) != "root" ]; then
    error "must be executed as root."
    exit 1
fi

for _arch in ${BSDKIT_ARCH_LIST}; do
    for _version in ${BSDKIT_VERSION_LIST}; do
        ${SCRIPT_PATH}/bsdkit-build -v ${_version} -a ${_arch} -A "$@"
    done
done
