#!/bin/sh

set -e -u

for _arch in ${BSDKIT_ARCH_LIST}; do
    for _version in ${BSDKIT_VERSION_LIST}; do
        if [ -d ${BSDKIT_PATH}/release-${_version}-${_arch} ]; then
            sudo -E rsync -avP --delete ${USER}@${BSDKIT_REMOTE}/release-${_version}-${_arch}/ \
                 ${BSDKIT_PATH}/release-${_version}-${_arch}/
        fi

        mkdir -p ${BSDKIT_PATH}/src/${_version}/release-${_arch}/ftp

        if [ -d ${BSDKIT_PATH}/src/${_version}/release-${_arch}/ftp ]; then
            sudo -E rsync -avP --delete ${BSDKIT_PATH}/release-${_version}-${_arch}/ \
                 ${BSDKIT_PATH}/src/${_version}/release-${_arch}/ftp/
        fi

        sudo -E rsync -avP ${USER}@${BSDKIT_REMOTE}/release-${_version}-${_arch}.iso ${BSDKIT_PATH}/
        sudo -E rsync -avP ${USER}@${BSDKIT_REMOTE}/release-${_version}-${_arch}.img ${BSDKIT_PATH}/
    done
done
