#!/bin/sh

set -e -u

which cpdup > /dev/null

: ${SITE_ROOT:=http://olgeni.olgeni.com/FreeBSD}
: ${VERSION:=11.0}
: ${ARCH:=amd64}
: ${DESTDIR:=}

_source=host
_srcdir=/usr/src

while getopts "r:v:a:d:j" OPT; do
    case $OPT in
        r)
            SITE_ROOT=${OPTARG}
            ;;
        v)
            VERSION=${OPTARG}
            ;;
        a)
            ARCH=${OPTARG}
            ;;
        d)
            DESTDIR=${OPTARG%/}
            ;;
        j)
            _source=jail
            ;;
        *)
            exit 64 # EX_USAGE
    esac
done

shift $((${OPTIND} - 1))

if [ "${_source}" == "jail" ]; then
    _srcdir=${DESTDIR}/usr/src
fi

if [ -f ${_srcdir}/Makefile ]; then
    etcupdate resolve -s ${_srcdir} -D ${DESTDIR}/
fi

_release=${SITE_ROOT}/release-${VERSION}-${ARCH}

_distdir=/usr/freebsd-dist/${VERSION}-${ARCH}

extract()
{
    local _src=""
    local _dst=""
    local _options=""
    local _exclude=""
    local _chdir=""

    while getopts "s:d:x:C:o" OPT; do
        case $OPT in
            s)
                _src=${OPTARG}
                ;;
            d)
                _dst=${OPTARG}
                ;;
            x)
                _exclude="${OPTARG}"
                ;;
            C)
                _chdir="${OPTARG}"
                ;;
            o)
                _options="${_options} -o"
                ;;
            *)
                exit 64 # EX_USAGE
        esac
    done

    [ -f ${_src} ]
    [ -d ${_dst} ]

    _dst="$(echo ${_dst} | sed -e "s@//@/@")"

    find ${_distdir}/__staging__ -flags -schg -exec chflags noschg {} \; > /dev/null 2>&1 || :
    rm -r -f ${_distdir}/__staging__

    mkdir -p ${_distdir}/__staging__

    if [ -n "${_exclude}" ]; then
        echo "${_exclude}" | rs 0 1 > ${_distdir}/__staging__/.cpignore
    fi

    tar -x -z -U -f ${_src} -C ${_distdir}/__staging__

    cpdup ${_options} -x -l -VV ${_distdir}/__staging__/${_chdir} ${_dst}

    find ${_distdir}/__staging__ -flags -schg -exec chflags noschg {} \; > /dev/null 2>&1 || :

    rm -r -f ${_distdir}/__staging__ > /dev/null 2>&1
}

mkdir -p ${_distdir}

cd ${_distdir}

fetch ${_release}/MANIFEST

cat MANIFEST | cut -f 1 | while read _file; do
    _sha256=$(awk "\$1 == \"${_file}\" { print \$2 }" < MANIFEST)

    if [ -e "${_file}" ]; then
        echo "Checking ${_file}"
        _sha256_local=$(sha256 -q "${_file}")
    else
        _sha256_local="0"
    fi

    while [ "${_sha256}" != "${_sha256_local}" ]; do
        fetch ${_release}/${_file}
        _sha256_local=$(sha256 -q "${_file}")
    done
done

export PATH=/rescue:${PATH}

if [ -f ${_srcdir}/Makefile ]; then
    etcupdate -p -s ${_srcdir} -D ${DESTDIR}/
fi

if [ ${_source} = host -a -z "${DESTDIR}" ] || [ ${_source} = jail ]; then
    if [ -d ${_srcdir} ]; then
        echo "Extracting: src.txz"

        for _file in ${_srcdir}/*; do
            rm -r -f  ${_file}
        done

        extract -o -s ${_distdir}/src.txz -C /usr/src -d ${DESTDIR}/usr/src
    fi
fi

find ${DESTDIR}/bin       \
     ${DESTDIR}/lib       \
     ${DESTDIR}/libexec   \
     ${DESTDIR}/sbin      \
     ${DESTDIR}/usr/bin   \
     ${DESTDIR}/usr/lib   \
     ${DESTDIR}/usr/lib32 \
     -flags -schg         \
     -exec chflags noschg {} \;

if [ -f ${_srcdir}/Makefile ]; then
    etcupdate -p -s ${_srcdir} -D ${DESTDIR}/
fi

if [ -f "${DESTDIR}/boot/kernel/kernel" ]; then
    echo "Extracting: kernel.txz"
    extract -o -s ${_distdir}/kernel.txz -d ${DESTDIR}/
fi

echo "Extracting: base.txz"
extract -o -s ${_distdir}/base.txz -d ${DESTDIR}/ -x ".cshrc .profile dev etc media mnt proc root tmp var"

echo "Extracting: doc.txz"
extract -o -s ${_distdir}/doc.txz -d ${DESTDIR}/

if [ -f ${_distdir}/games.txz ]; then
    echo "Extracting: games.txz"
    extract -o -s ${_distdir}/games.txz -d ${DESTDIR}/
fi

if [ -f ${_distdir}/lib32.txz ]; then
    echo "Extracting: lib32.txz"
    extract -o -s ${_distdir}/lib32.txz -d ${DESTDIR}/
fi

echo "Running: mtree"

mtree -ideU -f /etc/mtree/BSD.root.dist -p ${DESTDIR}/
mtree -ideU -f /etc/mtree/BSD.var.dist  -p ${DESTDIR}/var
mtree -ideU -f /etc/mtree/BSD.usr.dist  -p ${DESTDIR}/usr

if [ -f ${_srcdir}/Makefile ]; then
    echo "Running: etcupdate"
    etcupdate -F -I '*.cf' -s ${_srcdir} -D ${DESTDIR}/
fi

etcupdate resolve -s ${_srcdir} -D ${DESTDIR}/

chroot ${DESTDIR} newaliases

if [ -f ${_srcdir}/Makefile ]; then
    cd ${_srcdir}

    echo "Running: delete-old"
    yes y | make delete-old DESTDIR=${DESTDIR}/ > /dev/null 2>&1

    # echo "Running: delete-old-libs"
    # yes y | make delete-old-libs DESTDIR=${DESTDIR}/ > /dev/null 2>&1
fi

# gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 ada0
# gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 ada1
