#!/bin/sh

set -e -u

for _arch in ${BSDKIT_ARCH_LIST}; do
    for _version in ${BSDKIT_VERSION_LIST}; do
        sudo -E rsync -avP --delete ${BSDKIT_PATH}/src/${_version}/release-${_arch}/ftp/ \
             ${BSDKIT_PATH}/release-${_version}-${_arch}/

        rsync -avP --delete ${BSDKIT_PATH}/release-${_version}-${_arch}/ \
              ${BSDKIT_REMOTE}/release-${_version}-${_arch}/

        rsync -avP ${BSDKIT_PATH}/release-${_version}-${_arch}.iso ${BSDKIT_REMOTE}/
        rsync -avP ${BSDKIT_PATH}/release-${_version}-${_arch}.img ${BSDKIT_REMOTE}/
    done
done
