#!/bin/sh

set -e -u

for _arch in ${BSDKIT_ARCH_LIST}; do
    for _version in ${BSDKIT_VERSION_LIST}; do
        if [ -d ${BSDKIT_PATH}/src/${_version}/release-${_arch}/ftp ]; then
            sudo -E rsync -avP --delete ${BSDKIT_PATH}/src/${_version}/release-${_arch}/ftp/ \
                ${BSDKIT_PATH}/release-${_version}-${_arch}/
        fi

        if [ -d ${BSDKIT_PATH}/release-${_version}-${_arch} ]; then
            rsync -avP --delete ${BSDKIT_PATH}/release-${_version}-${_arch}/ \
                ${BSDKIT_REMOTE}/release-${_version}-${_arch}/
        fi

        if [ -f ${BSDKIT_PATH}/release-${_version}-${_arch}.iso ]; then
            rsync -avP ${BSDKIT_PATH}/release-${_version}-${_arch}.iso ${BSDKIT_REMOTE}/
        fi

        if [ -f ${BSDKIT_PATH}/release-${_version}-${_arch}.img ]; then
            rsync -avP ${BSDKIT_PATH}/release-${_version}-${_arch}.img ${BSDKIT_REMOTE}/
        fi
    done
done
