#!/bin/sh

set -e -u

for _version in ${BSDKIT_VERSIONS}; do
    sudo -E rsync -avP --delete ${BSDKIT_LOCAL}/src/${_version}/release-${BSDKIT_ARCH}/ftp/ \
         ${BSDKIT_LOCAL}/release-${_version}-${BSDKIT_ARCH}/

    rsync -avP --delete ${BSDKIT_LOCAL}/release-${_version}-${BSDKIT_ARCH}/ \
          ${BSDKIT_REMOTE}/release-${_version}-${BSDKIT_ARCH}/

    rsync -avP ${BSDKIT_LOCAL}/release-${_version}-${BSDKIT_ARCH}.iso ${BSDKIT_REMOTE}/
    rsync -avP ${BSDKIT_LOCAL}/release-${_version}-${BSDKIT_ARCH}.img ${BSDKIT_REMOTE}/
done
