#!/bin/sh

set -e -u

_bootfs=$(zpool get -H -p -o value bootfs 2>/dev/null | grep -v "^-")

if [ $? = 0 ]; then
    _bootenv_base=$(dirname ${_bootfs})

    zfs list -H -o name -r ${_bootenv_base} \
        | grep -v "^${_bootenv_base}$" \
        | while read _fs; do

        echo -n "Checking property 'canmount' on ${_fs}: "

        if [ "$(zfs get -H -o value canmount ${_fs})" != noauto ]; then
            zfs set canmount=noauto ${_fs}
            echo "changed."
        else
            echo "ok."
        fi
    done
fi
