#!/bin/sh

# shellcheck disable=SC3043

set -e -u

error() {
    echo "bsdkit-rewrite-filesystem: $*"
    exit 1
}

filter_properties() {
    awk '
BEGIN {
  read_only["available"] = 1;
  read_only["casesensitivity"] = 1;
  read_only["compressratio"] = 1;
  read_only["createtxg"] = 1;
  read_only["creation"] = 1;
  read_only["encryption"] = 1;
  read_only["filesystem_count"] = 1;
  read_only["guid"] = 1;
  read_only["keyformat"] = 1;
  read_only["keylocation"] = 1;
  read_only["logicalreferenced"] = 1;
  read_only["logicalused"] = 1;
  read_only["mlslabel"] = 1;
  read_only["mounted"] = 1;
  read_only["normalization"] = 1;
  read_only["objsetid"] = 1;
  read_only["pbkdf2iters"] = 1;
  read_only["refcompressratio"] = 1;
  read_only["referenced"] = 1;
  read_only["snapshot_count"] = 1;
  read_only["type"] = 1;
  read_only["used"] = 1;
  read_only["usedbychildren"] = 1;
  read_only["usedbydataset"] = 1;
  read_only["usedbyrefreservation"] = 1;
  read_only["usedbysnapshots"] = 1;
  read_only["utf8only"] = 1;
  read_only["version"] = 1;
  read_only["written"] = 1;
}

{
  if (!read_only[$2]) {
    print;
  }
}
'
}

rewrite_filesystem() {
    local _option

    local _source_filesystem

    OPTIND=1
    while getopts "s:" _option; do
        case "${_option}" in
            s)
                _source_filesystem="${OPTARG}"
                ;;
            *)
                error "unrecognized option."
                ;;
        esac
    done

    [ -n "${_source_filesystem}" ] || error "_source_filesystem required."

    local _target_filesystem
    local _snapshot_name

    _snapshot_name=$(uuidgen | cut -d - -f 1)
    _target_filesystem=${_source_filesystem}.${_snapshot_name}

    zfs destroy -r "${_source_filesystem}"@"${_snapshot_name}" >/dev/null 2>&1 || :
    zfs unmount -f "${_source_filesystem}"
    zfs snapshot -r "${_source_filesystem}"@"${_snapshot_name}"
    zfs send --verbose --replicate --props --large-block --embed "${_source_filesystem}"@"${_snapshot_name}" \
        | zfs receive -v -u -F "${_target_filesystem}"
    zfs destroy -r -f "${_source_filesystem}"@"${_snapshot_name}"
    zfs destroy -r -f "${_target_filesystem}"@"${_snapshot_name}"
    zfs destroy -r -f "${_source_filesystem}"
    zfs rename "${_target_filesystem}" "${_source_filesystem}"

    for _filesystem in $(zfs list -H -o name -t filesystem -r "${_source_filesystem}"); do
        # BD584E0F-28D6-4409-956D-F9B1468C2DD9
        zfs get -H all "${_filesystem}" \
            | filter_properties \
            | cut -s -f 2 \
            | sort \
            | uniq \
            | xargs -n1 -J % echo zfs inherit -S % "${_filesystem}" \
            | sh -x
    done

    # 8E95F488-BE4B-48F6-9FEE-C58CBBFD25BC
    zfs get -s received -H -r all "${_source_filesystem}" \
        | filter_properties \
        | awk '
$2 != "mountpoint" {
  print "zfs set " $2 "=" $3 " " $1;
}

$2 == "mountpoint" {
  gsub("/altroot", "", $3);

  if ($3 == "") {
    $3 = "/";
  }

  print "zfs set " $2 "=" $3 " " $1
}
' | sh -x

    if [ "$(zfs get -H -o value canmount "${_source_filesystem}")" = "on" ]; then
        zfs mount "${_source_filesystem}"
    fi
}

rewrite_filesystem "$@"
