#!/bin/sh

set -e -u

SCRIPT_NAME=$(basename $0)

error ()
{
    echo "${SCRIPT_NAME}: $@"
    exit 1
}

if [ $(whoami) != "root" ]; then
    error "must be executed as root."
    exit 1
fi

: ${BSDKIT_WITH_SITE:=""}

_version=$1
_arch=$2

_iso=${BSDKIT_PATH}/release-${_version}-${_arch}.iso
_img=${BSDKIT_PATH}/release-${_version}-${_arch}.img

if [ -n "${BSDKIT_WITH_SITE}" ]; then
    _iso=${BSDKIT_PATH}/release-${_version}-${_arch}.full.iso
    _img=${BSDKIT_PATH}/release-${_version}-${_arch}.full.img
fi

OS_SRCDIR=${BSDKIT_PATH}/src/${_version}/src
OS_RELDIR=${BSDKIT_PATH}/src/${_version}/release-${_arch}
OS_MAJOR=$(echo ${_version} | sed -e "s/\\..*//")

# ===

./bsdkit build_setup_img ${_iso} ${_img}
