#!/bin/sh

set -e -u

unset POSIXLY_CORRECT

SCRIPT_NAME=$(basename $0)

error()
{
    echo "${SCRIPT_NAME}: $@"
    exit 1
}

if [ $(whoami) != "root" ]; then
    error "must be executed as root."
    exit 1
fi

: ${_with_site:=""}

_jobs="$(sysctl -n hw.ncpu)"

while getopts "j:" OPT; do
    case ${OPT} in
        j)
            _jobs="${OPTARG}"
            ;;
        *)
    esac
done

shift $((${OPTIND} - 1))

_jobs_option="-j${_jobs}"

_version=$1
_arch=$2

# ===

OS_SRCDIR=${BSDKIT_PATH}/src/${_version}/src
OS_RELDIR=${BSDKIT_PATH}/src/${_version}/release-${_arch}
OS_MAJOR=$(echo ${_version} | sed -e "s/\\..*//")

# ===

_iso=${BSDKIT_PATH}/release-${_version}-${_arch}.iso
_release="none"
_packages="none"

if [ -n "${_with_site}" ]; then
    _iso=${BSDKIT_PATH}/release-${_version}-${_arch}.full.iso
    _release=${BSDKIT_PATH}/release-${_version}-${_arch}
    _packages=${BSDKIT_PATH}/packages-FreeBSD:${OS_MAJOR}:${_arch}-default-nox11
fi

./bsdkit build_setup_iso ${_iso} ${BSDKIT_PATH}/staging-${_version}-${_arch} ${_release} ${_packages}
