#!/bin/sh

set -e -u

unset POSIXLY_CORRECT

SCRIPT_NAME=$(basename $0)

error()
{
    echo "${SCRIPT_NAME}: $@"
    exit 1
}

if [ $(whoami) != "root" ]; then
    error "must be executed as root."
    exit 1
fi

: ${_with_site:=""}

_jobs="$(sysctl -n hw.ncpu)"

while getopts "j:" OPT; do
    case ${OPT} in
        j)
            _jobs="${OPTARG}"
            ;;
        *)
    esac
done

shift $((${OPTIND} - 1))

_jobs_option="-j${_jobs}"

_version=$1
_arch=$2

# ===

OS_SRCDIR=${BSDKIT_PATH}/src/${_version}/src
OS_RELDIR=${BSDKIT_PATH}/src/${_version}/release-${_arch}
OS_MAJOR=$(echo ${_version} | sed -e "s/\\..*//")

# ===

./build-release ${_version} ${_arch}
./build-staging ${_version} ${_arch}
./build-iso ${_version} ${_arch}
./build-img ${_version} ${_arch}

echo "Build complete for ${_version} ${_arch}"
