---
- name: "mysql-zfs: check contents of MySQL home directory"
  find:
    paths: /var/db/mysql
    recurse: true
    hidden: true
  register: find_var_db_mysql

- name: "mysql-zfs: gather facts about MySQL ZFS dataset"
  community.general.zfs_facts:
    dataset: "{{ boot_pool }}/var/db/mysql"
  ignore_errors: true
  register: mysql_zfs_facts

- name: "mysql-zfs: create ZFS dataset for MySQL"
  when: find_var_db_mysql.matched == 0 or mysql_zfs_facts is successful
  zfs:
    name: "{{ boot_pool }}/var/db/mysql"
    state: present
    extra_zfs_properties:
      canmount: true
      compression: "{{ zfs_compression }}"
      atime: false
      redundant_metadata: most
