---
- name: Update /etc/rc.conf.d/ntpd
  lineinfile:
    path: /etc/rc.conf.d/ntpd
    regexp: '^ntp_leapfile_sources='
    line: 'ntp_leapfile_sources="{{ ntp_leapfile_sources }}"'
    state: present
    create: true

- name: Check if ntpd is enabled
  shell:
    cmd: |
      [ "$(sysrc -n ntpd_enable)" = "YES" ]
  register: sysrc_ntpd_enabled
  changed_when: false
  failed_when: false

- name: Update ntpd files
  when: sysrc_ntpd_enabled.rc == 0
  block:
    - name: Check if ntpd needs to fetch new files
      command: /etc/rc.d/ntpd needfetch
      register: ntpd_needfetch
      changed_when: false
      failed_when: false

    - name: Fetch new ntpd files
      command:
        cmd: |
          /etc/rc.d/ntpd fetch
      when: ntpd_needfetch.rc == 0
      changed_when: true
      notify:
        - restart_ntpd
