#!/bin/sh

# e41c5c63-185f-43e8-a8e9-bf89a0bf0256

set -o errexit -o nounset -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(grep -v '^\s*#' envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(grep -v '^\s*#' envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/* | grep -v '^\s*#')"
fi

ENV_ARGS=""
if [ -n "${ENVRC}" ]; then
    ENV_ARGS="-S \"${ENVRC}\""
fi

: ${GUNICORN_USER:="nobody"}
: ${GUNICORN_PATH:="/tmp"}
: ${GUNICORN_ARGS=""}
: ${GUNICORN_APP:="app:app"}
: ${GUNICORN_VENV:="${GUNICORN_PATH}/.venv"}
: ${GUNICORN_PYTHON:="python3"}
: ${GUNICORN_PYTHON_FLAGS=""}
: ${GUNICORN_UV:=""}

cd ${GUNICORN_PATH}

export OSTYPE=freebsd

. ${GUNICORN_VENV}/bin/activate

if [ "$(id -u)" = "0" ]; then
    CHPST_COMMAND="chpst -u ${GUNICORN_USER} ${CHPST_ARGS}"
fi

PYTHON_PREFIX=""
if [ -n "${GUNICORN_UV}" ]; then
    PYTHON_PREFIX="uv run "
fi

exec env ${ENV_ARGS} ${CHPST_COMMAND:-} ${PYTHON_PREFIX}${GUNICORN_PYTHON} ${GUNICORN_PYTHON_FLAGS} -m gunicorn ${GUNICORN_ARGS} ${GUNICORN_APP}

# For logs: "--log-level debug"
# For uvicorn support: "--worker-class uvicorn.workers.UvicornWorker"
# For proxy address resolution: "--forwarded-allow-ips=*"
# For Unix socket: "--bind unix:/var/run/app.sock"
