#!/bin/sh

# E41C5C63-185F-43E8-A8E9-BF89A0BF0256

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . $(realpath config)

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC}$(cat envrc.local)"
fi

: ${GUNICORN_USER:="nobody"}
: ${GUNICORN_PATH:="/tmp"}
: ${GUNICORN_ARGS=""}
: ${GUNICORN_APP:="app:app"}
: ${GUNICORN_VENV:="${GUNICORN_PATH}/.venv"}

cd ${GUNICORN_PATH}

. ${GUNICORN_VENV}/bin/activate

exec env -S "${ENVRC}" chpst -u ${GUNICORN_USER} ${CHPST_ARGS} gunicorn ${GUNICORN_ARGS} ${GUNICORN_APP}

# For logs: "--log-level debug"
# For uvicorn support: "--worker-class uvicorn.workers.UvicornWorker"
