---
- name: bsdkit_vmware
  when: is_host_install and platform_is_vmware
  block:
    - name: Install packages
      community.general.pkgng:
        name:
          - emulators/open-vm-tools
        state: present

    - name: Enable VMware guest
      lineinfile:
        dest: /etc/rc.conf
        line: '{{ item }}_enable="YES"'
        regexp: ^{{ item }}_enable
        insertafter: EOF
      with_items:
        - vmware_guest_vmblock
        - vmware_guest_vmhgfs
        - vmware_guest_vmmemctl
        - vmware_guest_vmxnet
        - vmware_guestd
