---
- name: Add MySQL group
  group:
    name: mysql
    gid: 88
    state: present

- name: Add MySQL user
  user:
    name: mysql
    uid: 88
    group: mysql
    home: /var/db/mysql
    shell: /bin/sh
    state: present
    createhome: false

- name: Create home directory for MySQL
  file:
    path: /var/db/mysql
    state: directory
    mode: "0755"
    owner: mysql
    group: mysql

- name: Check if /var/db/mysql is empty
  find:
    paths: /var/db/mysql
    file_type: any
  register: find_mysql_db_dir
  changed_when: false

- name: Set fact if /var/db/mysql is empty
  set_fact:
    mysql_db_dir_empty: "{{ find_mysql_db_dir.matched == 0 }}"
  changed_when: false

- name: Check if legacy MySQL PID file exists
  stat:
    path: /var/db/mysql/{{ ansible_nodename }}.pid
  register: stat_mysql_pidfile
  changed_when: false
  failed_when: false

- name: Migrate legacy MySQL pidfile
  copy:
    src: /var/db/mysql/{{ ansible_nodename }}.pid
    dest: /var/db/mysql/mysqld.pid
    owner: mysql
    group: mysql
    mode: "0640"
  when: stat_mysql_pidfile.stat.exists

- name: Create /etc/rc.conf.d/mysql
  copy:
    dest: /etc/rc.conf.d/mysql
    content: |
      mysql_pidfile=/var/db/mysql/mysqld.pid
    owner: root
    group: wheel
    mode: "0644"

- name: Configure SSH identity for MySQL
  when: not mysql_db_dir_empty
  block:
    - name: Create SSH directory for MySQL
      file:
        path: /var/db/mysql/.ssh
        state: directory
        mode: "0700"
        owner: mysql
        group: mysql

    - name: Create SSH identity for MySQL
      community.crypto.openssh_keypair:
        path: /var/db/mysql/.ssh/id_ed25519
        comment: mysql@{{ ansible_hostname }}
        type: ed25519
        owner: mysql
        group: mysql
