---
- name: Add MySQL group
  group:
    name: mysql
    gid: 88
    state: present

- name: Add MySQL user
  user:
    name: mysql
    uid: 88
    group: mysql
    home: /var/db/mysql
    shell: /bin/sh
    state: present

- name: Create home directory for MySQL
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: mysql
    group: mysql
  with_items:
    - /var/db/mysql
    - /var/db/mysql/.ssh

- name: Create ssh identity for MySQL
  community.crypto.openssh_keypair:
    path: /var/db/mysql/.ssh/id_ed25519
    comment: mysql@{{ ansible_hostname }}
    type: ed25519
    owner: mysql
    group: mysql
