---
- name: Add MySQL group
  group:
    name: mysql
    gid: 88
    state: present

- name: Add MySQL user
  user:
    name: mysql
    uid: 88
    group: mysql
    home: /var/db/mysql
    shell: /bin/sh
    state: present

- name: Create home directory for MySQL
  file:
    path: /var/db/mysql
    state: directory
    mode: "0755"
    owner: mysql
    group: mysql

- name: Check if /var/db/mysql is empty
  shell: ls -A /var/db/mysql
  register: ls_mysql_db_dir
  changed_when: false
  failed_when: false

- name: Create /etc/rc.conf.d/mysql
  copy:
    dest: /etc/rc.conf.d/mysql
    content: |
      mysql_pidfile=/var/db/mysql/mysqld.pid
    owner: root
    group: wheel
    mode: "0644"

- name: Configure SSH identity for MySQL
  when: ls_mysql_db_dir.stdout != ""
  block:
    - name: Create SSH directory for MySQL
      file:
        path: /var/db/mysql/.ssh
        state: directory
        mode: "0700"
        owner: mysql
        group: mysql

    - name: Create SSH identity for MySQL
      community.crypto.openssh_keypair:
        path: /var/db/mysql/.ssh/id_ed25519
        comment: mysql@{{ ansible_hostname }}
        type: ed25519
        owner: mysql
        group: mysql
