---
- name: Install packages (benthos)
  community.general.pkgng:
    name: "{{ item }}"
    state: present
  loop:
    - net/benthos

- name: Create /var/db/runit/{{ bsdkit_service_name }}
  file:
    mode: "0755"
    path: /var/db/runit/{{ bsdkit_service_name }}
    state: directory

- name: Create /var/db/runit/{{ bsdkit_service_name }}/data
  file:
    mode: "0755"
    path: /var/db/runit/{{ bsdkit_service_name }}/data
    state: directory

- name: Create /var/db/runit/{{ bsdkit_service_name }}/resources
  file:
    mode: "0755"
    path: /var/db/runit/{{ bsdkit_service_name }}/resources
    state: directory

- name: Copy Benthos configuration files
  template:
    src: "{{ item }}"
    dest: "/var/db/runit/{{ bsdkit_service_name }}/{{ item | basename }}"
    group: wheel
    mode: "0644"
  with_items: "{{ bsdkit_sv_benthos_configuration }}"
  notify:
    - restart_sv_benthos

- name: Copy Benthos resource files
  template:
    src: "{{ item }}"
    dest: "/var/db/runit/{{ bsdkit_service_name }}/resources/{{ item | basename }}"
    group: wheel
    mode: "0644"
  with_items: "{{ bsdkit_sv_benthos_resources }}"
  notify:
    - restart_sv_benthos

- name: Copy /var/db/runit/{{ bsdkit_service_name }}/run
  copy:
    dest: /var/db/runit/{{ bsdkit_service_name }}/run
    group: wheel
    src: ../files/run
    mode: "0755"
  notify:
    - restart_sv_benthos

- name: Copy /var/db/runit/{{ bsdkit_service_name }}/benthos.yml.sample
  copy:
    dest: /var/db/runit/{{ bsdkit_service_name }}/benthos.yml.sample
    group: wheel
    src: ../files/benthos.yml.sample
    mode: "0644"
  notify:
    - restart_sv_benthos

- name: Link /var/service/{{ bsdkit_service_name }}
  file:
    src: /var/db/runit/{{ bsdkit_service_name }}
    path: /var/service/{{ bsdkit_service_name }}
    state: link
  notify:
    - restart_sv_benthos
