---
- name: bsdkit_loader
  when: is_host_install
  block:
    - name: Stat /boot/loader.conf
      stat:
        path: /boot/loader.conf
      register: stat_boot_loader_conf

    - name: Touch /boot/loader.conf
      file:
        path: /boot/loader.conf
        state: touch
        mode: "0644"
      changed_when: false
      when: not stat_boot_loader_conf.stat.exists

    - name: Configure loader_conf_files
      lineinfile:
        dest: /boot/loader.conf.local
        line: loader_conf_files="/boot/loader.conf.vendor /boot/device.hints /boot/loader.conf /boot/loader.conf.local"
        regexp: ^loader_conf_files=
        insertbefore: BOF
        create: true
        mode: "0644"

    - name: Install loader.conf.vendor
      copy:
        src: ../ansible/{{ item }}
        dest: /boot/{{ item }}
        owner: root
        group: wheel
        mode: "0644"
      with_items:
        - loader.conf.vendor
