---
- name: bsdkit_loader
  when: is_host_install
  block:
    - name: Stat /boot/loader.conf.local
      stat:
        path: /boot/loader.conf.local
      register: stat_boot_loader_conf_local

    - name: Touch /boot/loader.conf.local
      file:
        path: /boot/loader.conf.local
        state: touch
        mode: "0644"
      when: not stat_boot_loader_conf_local.stat.exists

    - name: Create /boot/loader.conf.d directory
      file:
        path: /boot/loader.conf.d
        state: directory
        mode: "0755"

    - name: Include tasks from migrate_loader_conf.yml
      include_tasks: migrate_loader_conf.yml

    - name: Install loader.conf
      copy:
        src: ../ansible/{{ item }}
        dest: /boot/{{ item }}
        owner: root
        group: wheel
        mode: "0644"
      with_items:
        - loader.conf

    - name: Configure loader.conf.local
      when: bsdkit.loader_conf is defined
      lineinfile:
        dest: /boot/loader.conf.local
        line: '{{ item.key }}="{{ item.value }}"'
        regexp: ^{{ item.key }} *=
        create: true
        mode: "0644"
        state: present
      with_items: "{{ bsdkit.loader_conf | dict2items }}"

    - name: Configure loader.conf.local (delete)
      when: bsdkit.loader_conf_delete is defined
      lineinfile:
        dest: /boot/loader.conf.local
        regexp: ^{{ item.key }} *=
        mode: "0644"
        state: absent
      with_items: "{{ bsdkit.loader_conf_delete | dict2items }}"

    - name: Stat /root/loader.conf.orig
      stat:
        path: /root/loader.conf.orig
      register: stat_root_loader_conf_orig

    - name: Stat /root/loader.conf.local.orig
      stat:
        path: /root/loader.conf.local.orig
      register: stat_root_loader_conf_local_orig

    - name: Remove /root/loader.conf.orig if empty
      when: stat_root_loader_conf_orig.stat.exists and stat_root_loader_conf_orig.stat.size == 0
      file:
        path: /root/loader.conf.orig
        state: absent

    - name: Remove /root/loader.conf.local.orig if empty
      when: stat_root_loader_conf_local_orig.stat.exists and stat_root_loader_conf_local_orig.stat.size == 0
      file:
        path: /root/loader.conf.local.orig
        state: absent
