---
- name: bsdkit_zfs
  when: is_host_install and zfs_available
  block:
    - name: Create /etc/zfs/zpool.cache
      shell:
        cmd: |
          zpool set cachefile=/etc/zfs/zpool.cache {{ boot_pool }}
        creates: /etc/zfs/zpool.cache

    - name: Create ZFS dataset for /var/db
      community.general.zfs:
        name: "{{ boot_pool }}/var/db"
        state: present
        extra_zfs_properties:
          canmount: false

    - name: Create ZFS dataset for /jails
      community.general.zfs:
        name: "{{ boot_pool }}/jails"
        state: present

    - name: Create ZFS dataset for /usr/local
      community.general.zfs:
        name: "{{ boot_pool }}/usr/local"
        state: present
        extra_zfs_properties:
          canmount: false

    - name: Gather facts about pkg ZFS dataset
      community.general.zfs_facts:
        dataset: "{{ boot_pool }}/usr/local/pkg"
      register: zfs_facts_usr_local_pkg
      failed_when: false

    - name: Remove usr/local/pkg
      when: zfs_facts_usr_local_pkg is succeeded
      block:
        - name: Save /var/db/pkg
          shell: |
            set -e -u -o pipefail
            mkdir /tmp/pkg/
            mv /var/db/pkg/* /tmp/pkg/
          changed_when: true

        - name: Destroy ZFS dataset for pkg
          community.general.zfs:
            name: "{{ boot_pool }}/usr/local/pkg"
            state: absent

        - name: Restore /var/db/pkg
          shell: |
            set -e -u -o pipefail
            mkdir -p /usr/local/pkg
            rm -r -f /var/db/pkg
            ln -s -f /usr/local/pkg /var/db/pkg
            mv /tmp/pkg/* /var/db/pkg/
            rmdir /tmp/pkg
          changed_when: true
