---
- name: Install packages
  community.general.pkgng:
    name:
      - security/sudo
    state: present

- name: Install default sudoers
  copy:
    src: /usr/local/etc/sudoers.dist
    dest: /usr/local/etc/sudoers
    owner: root
    group: wheel
    mode: "0644"
    remote_src: true

- name: Install sudoers files
  copy:
    src: "{{ item }}"
    dest: /usr/local/etc/sudoers.d/
    owner: root
    group: wheel
    mode: "0644"
  with_fileglob:
    - ../ansible/sudoers.d/*
