---
- name: Install packages
  community.general.pkgng:
    name:
      - devel/git
    state: present

- name: Install files into /usr/local/bsdkit/
  git:
    repo: https://gitlab.com/olgeni/bsdkit.git
    dest: /usr/local/bsdkit/
    single_branch: true
    version: master
    force: true
    update: true

- name: Create ansible role directory
  file:
    path: /usr/local/etc/ansible/roles
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: Ansible role cleanup
  shell:
    cmd: find -L /usr/local/etc/ansible/roles -type l -exec rm -- {} +
  changed_when: false

- name: Get role list
  find:
    paths: /usr/local/bsdkit/playbook/roles
    file_type: directory
  register: role_list
  changed_when: false
  failed_when: false

- name: Link Ansible roles
  when: role_list.matched > 0
  file:
    src: "{{ item }}"
    dest: "/usr/local/etc/ansible/roles/{{ item | basename }}"
    state: link
    owner: root
    group: wheel
    mode: "0755"
  loop: "{{ role_list.files | map(attribute='path') | list }}"

- name: Create symlink from /usr/local/bsdkit/bsdkit to /usr/local/sbin/bsdkit
  file:
    src: /usr/local/bsdkit/bsdkit
    dest: /usr/local/sbin/bsdkit
    state: link
    owner: root
    group: wheel
    mode: "0755"
