---
- name: "bsdkit-git: install packages"
  community.general.pkgng:
    name:
      - devel/git
    state: present

- name: "bsdkit-git: install files into /usr/local/bsdkit/"
  git:
    repo: https://github.com/olgeni/bsdkit.git
    dest: /usr/local/bsdkit/
    single_branch: true
    version: master

- name: "bsdkit-git: create ansible role directory"
  file:
    path: /usr/local/etc/ansible/roles
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: "bsdkit-git: ansible role cleanup"
  shell:
    cmd: find -L /usr/local/etc/ansible/roles -type l -exec rm -- {} +
  changed_when: false

- name: "bsdkit-git: get role list"
  shell:
    cmd: |
      ls /usr/local/bsdkit/playbook/roles
  changed_when: false
  register: role_list
  ignore_errors: true

- name: "bsdkit-git: link ansible roles"
  when: role_list is success
  file:
    src: /usr/local/bsdkit/playbook/roles/{{ item }}
    dest: /usr/local/etc/ansible/roles/{{ item }}
    state: link
    owner: root
    group: wheel
    mode: "0755"
  with_items: "{{ role_list.stdout_lines }}"
