---
- name: Install packages
  community.general.pkgng:
    name:
      - devel/git
    state: present

- name: Install files into /usr/local/bsdkit/
  git:
    repo: https://github.com/olgeni/bsdkit.git
    dest: /usr/local/bsdkit/
    single_branch: true
    version: master

- name: Create ansible role directory
  file:
    path: /usr/local/etc/ansible/roles
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: Ansible role cleanup
  shell:
    cmd: find -L /usr/local/etc/ansible/roles -type l -exec rm -- {} +
  changed_when: false

- name: Get role list
  shell:
    cmd: |
      ls /usr/local/bsdkit/playbook/roles
  register: role_list
  changed_when: false
  failed_when: false

- name: Link ansible roles
  when: role_list.rc == 0
  file:
    src: /usr/local/bsdkit/playbook/roles/{{ item }}
    dest: /usr/local/etc/ansible/roles/{{ item }}
    state: link
    owner: root
    group: wheel
    mode: "0755"
  with_items: "{{ role_list.stdout_lines }}"
