---
- name: bsdkit_env
  when: is_host_install
  block:
    - name: Set bsdkit ifconfig in rc.conf
      when: (bsdkit_interface | length > 0) and (bsdkit_ifconfig | length > 0)
      command:
        cmd: sysrc ifconfig_{{ bsdkit_interface }}="{{ bsdkit_ifconfig }}"

    - name: Set bsdkit defaultrouter in rc.conf
      when: bsdkit_defaultrouter | length > 0
      command:
        cmd: sysrc defaultrouter="{{ bsdkit_defaultrouter }}"
