---
- name: Remove virtualbox-ose-additions
  community.general.pkgng:
    name: emulators/virtualbox-ose-additions
    state: absent

- name: Package cleanup
  shell:
    cmd: |
      set -e -u -o pipefail
      pkg autoremove -y
      pkg clean -a -y

- name: rc.conf cleanup
  shell:
    cmd: |
      sysrc -x vboxguest_enable || :
      sysrc -x vboxservice_enable || :
  notify:
    - reformat_rc_conf

- name: Remove /usr/freebsd-dist
  file:
    path: /usr/freebsd-dist
    state: absent

- name: Reset unused disk space
  shell:
    cmd: |
      set -e -u -o pipefail
      dd if=/dev/zero of=/zero bs=1m || :
      rm -f /zero

- name: Configure /etc/resolvconf.conf
  copy:
    content: |
      resolvconf="NO"
    dest: /etc/resolvconf.conf
    owner: root
    group: wheel
    mode: "0644"

- name: Create /etc/rc.d/digitalocean
  # when: platform_is_digitalocean
  copy:
    src: files/digitalocean
    dest: /etc/rc.d/digitalocean
    owner: root
    group: wheel
    mode: "0755"

- name: Enable digitalocean service
  # when: platform_is_digitalocean
  service:
    name: digitalocean
    enabled: true
    state: stopped

- name: Touch /firstboot
  file:
    path: /firstboot
    state: touch
    owner: root
    group: wheel
    mode: "0644"

- name: Reset log files
  shell:
    cmd: |
      for _file in /var/log/*; do
          : > ${_file}
      done
      newsyslog -C -v
      : > /root/.history
  changed_when: false
