---
- name: Remove virtualbox-ose-additions
  community.general.pkgng:
    name: emulators/virtualbox-ose-additions
    state: absent

- name: Package autoremove
  command:
    cmd: |
      pkg autoremove -y
  changed_when: false

- name: Package clean
  command:
    cmd: |
      pkg clean -a -y
  changed_when: false

- name: Remove vboxguest_enable from /etc/rc.conf
  lineinfile:
    path: /etc/rc.conf
    regexp: "^vboxguest_enable="
    state: absent
  notify:
    - reformat_rc_conf

- name: Remove vboxservice_enable from /etc/rc.conf
  lineinfile:
    path: /etc/rc.conf
    regexp: "^vboxservice_enable="
    state: absent
  notify:
    - reformat_rc_conf

- name: Remove /usr/freebsd-dist
  file:
    path: /usr/freebsd-dist
    state: absent

- name: Reset unused disk space
  shell:
    cmd: |
      set -e -u -o pipefail
      dd if=/dev/zero of=/zero bs=1m || :
      rm -f /zero
  changed_when: false

- name: Create /etc/rc.d/bsdkit_provision
  copy:
    src: files/bsdkit_provision
    dest: /etc/rc.d/bsdkit_provision
    owner: root
    group: wheel
    mode: "0755"

- name: Enable bsdkit_provision service
  service:
    name: bsdkit_provision
    enabled: true
    state: stopped

- name: Touch /firstboot
  file:
    path: /firstboot
    state: touch
    owner: root
    group: wheel
    mode: "0644"

- name: DigitalOcean block
  when: sysprep_target is defined and sysprep_target == "digitalocean"
  block:
    - name: Include sysprep_digitalocean.yml
      include_tasks: sysprep_digitalocean.yml

- name: AWS block
  when: sysprep_target is defined and sysprep_target == "aws"
  block:
    - name: Include sysprep_aws.yml
      include_tasks: sysprep_aws.yml

- name: Reset log files
  shell:
    cmd: |
      for _file in /var/log/*; do
          : > ${_file}
      done
  changed_when: false

- name: Run newsyslog -C -v
  shell:
    cmd: |
      newsyslog -C -v
  changed_when: false

- name: Create /etc/resolv.conf if it does not exist
  copy:
    content: |
      nameserver 8.8.8.8
    dest: /etc/resolv.conf
    owner: root
    group: wheel
    mode: "0644"

- name: Check enc0 interface
  shell:
    cmd: |
      ifconfig enc0
  register: ifconfig_enc0
  changed_when: false
  failed_when: false

- name: Configure enc0 interface
  lineinfile:
    path: /etc/rc.conf
    regexp: "^ifconfig_enc0="
    line: "ifconfig_enc0=\"up\""
    state: present
  when: ifconfig_enc0.rc == 0
  notify:
    - reformat_rc_conf

- name: Delete /root/.history
  file:
    path: /root/.history
    state: absent
