---
- name: Include boot_loader_conf_digitalocean.yml
  include_tasks: boot_loader_conf_digitalocean.yml

- name: Include rc_conf_digitalocean.yml
  include_tasks: rc_conf_digitalocean.yml

- name: Include sysctl_conf_digitalocean.yml
  include_tasks: sysctl_conf_digitalocean.yml

- name: Configure /etc/resolvconf.conf
  copy:
    content: |
      resolvconf="NO"
    dest: /etc/resolvconf.conf
    owner: root
    group: wheel
    mode: "0644"
