---
- name: Add PostgreSQL group
  group:
    name: postgres
    gid: "{{ postgres_user_gid }}"
    state: present

- name: Add PostgreSQL user
  user:
    name: postgres
    uid: "{{ postgres_user_uid }}"
    group: postgres
    home: /var/db/postgres
    shell: /bin/sh
    state: present
    create_home: false

- name: Create home directory for PostgreSQL
  file:
    path: /var/db/postgres
    state: directory
    mode: "0755"
    owner: postgres
    group: postgres

- name: Create ssh directory for PostgreSQL
  file:
    path: /var/db/postgres/.ssh
    state: directory
    mode: "0700"
    owner: postgres
    group: postgres

- name: Create ssh identity for PostgreSQL
  community.crypto.openssh_keypair:
    path: /var/db/postgres/.ssh/id_ed25519
    comment: postgres@{{ ansible_hostname }}
    type: ed25519
    owner: postgres
    group: postgres
