---
- name: Set 'MAILTO' in /etc/crontab
  lineinfile:
    dest: /etc/crontab
    line: MAILTO=""
    regexp: ^MAILTO
    insertbefore: ^SHELL=
  notify: restart_cron

- name: Add daily pkg clean job to /etc/crontab
  cron:
    name: "Clean package cache"
    minute: "30"
    hour: "3"
    user: root
    job: "/usr/sbin/pkg clean -a -y >/dev/null 2>&1"
    cron_file: pkg-clean
  notify: restart_cron

- name: Add daily bsdkit update job to /etc/crontab
  cron:
    name: "Update bsdkit"
    minute: "0"
    hour: "3"
    user: root
    job: "/usr/local/bsdkit/bsdkit update >/dev/null 2>&1"
    cron_file: bsdkit-update
  notify: restart_cron
