---
- name: "periodic: configure periodic.conf"
  when: periodic_conf is defined
  lineinfile:
    dest: /etc/periodic.conf
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: ^{{ item.key }} *=
    create: true
    mode: "0644"
    state: present
  with_items: "{{ periodic_conf | dict2items }}"

- name: "periodic: configure periodic.conf (delete)"
  when: periodic_conf_delete is defined
  lineinfile:
    dest: /etc/periodic.conf
    regexp: ^{{ item.key }} *=
    create: true
    mode: "0644"
    state: absent
  with_items: "{{ periodic_conf_delete | dict2items }}"
