---
- name: Configure periodic.conf
  when: bsdkit.periodic_conf is defined
  lineinfile:
    dest: /etc/periodic.conf
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: "^{{ item.key }} *="
    create: true
    mode: "0644"
    state: present
  with_items: "{{ bsdkit.periodic_conf | dict2items }}"

- name: Configure periodic.conf (delete)
  when: bsdkit.periodic_conf_delete is defined
  lineinfile:
    dest: /etc/periodic.conf
    regexp: "^{{ item.key }} *="
    create: true
    mode: "0644"
    state: absent
  with_items: "{{ bsdkit.periodic_conf_delete | dict2items }}"
