---
- name: "rc: configure rc.conf"
  when: rc_conf is defined
  lineinfile:
    dest: /etc/rc.conf
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: ^{{ item.key }} *=
    create: true
    mode: "0644"
    state: present
  with_items: "{{ rc_conf | dict2items }}"
  notify:
    - reformat_rc_conf

- name: "rc: configure rc.conf (delete)"
  when: rc_conf_delete is defined
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^{{ item.key }} *=
    mode: "0644"
    state: absent
  with_items: "{{ rc_conf_delete | dict2items }}"
  notify:
    - reformat_rc_conf
