---
- name: Configure rc.conf
  when: bsdkit.rc_conf is defined
  lineinfile:
    dest: /etc/rc.conf
    line: '{{ item.key }}="{{ item.value }}"'
    regexp: ^{{ item.key }} *=
    create: true
    mode: "0644"
    state: present
  with_items: "{{ bsdkit.rc_conf | dict2items }}"
  notify:
    - reformat_rc_conf

- name: Configure rc.conf (delete)
  when: bsdkit.rc_conf_delete is defined
  lineinfile:
    dest: /etc/rc.conf
    regexp: ^{{ item.key }} *=
    mode: "0644"
    state: absent
  with_items: "{{ bsdkit.rc_conf_delete | dict2items }}"
  notify:
    - reformat_rc_conf
