- name: "Set bsdkit ifconfig in rc.conf"
  command:
    cmd: sysrc ifconfig_{{ bsdkit_interface }}="{{ bsdkit_ifconfig }}"
  when: (bsdkit_interface | length > 0) and (bsdkit_ifconfig | length > 0)

- name: "Set bsdkit defaultrouter in rc.conf"
  command:
    cmd: sysrc defaultrouter="{{ bsdkit_defaultrouter }}"
  when: bsdkit_defaultrouter | length > 0
