---
- name: "ca-root-nss: install ca_root_nss"
  pkgng:
    name:
      - security/ca_root_nss
    state: present

- name: "ca-root-nss: create /usr/local/etc/ssl/certs"
  file:
    path: /usr/local/etc/ssl/certs
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: "ca-root-nss: link ca-root-nss.crt (stat: ca-root-nss.crt)"
  stat:
    path: /usr/local/share/certs/ca-root-nss.crt
  register: stat_ca_root_nss

- name: "ca-root-nss: link ca-root-nss.crt (stat: cert.pem)"
  stat:
    path: /usr/local/etc/ssl/cert.pem
  register: stat_cert_pem

- name: "ca-root-nss: link ca-root-nss.crt (exec)"
  file:
    src: /usr/local/share/certs/ca-root-nss.crt
    dest: /usr/local/etc/ssl/cert.pem
    state: link
    owner: root
    group: wheel
    mode: "0644"
  when: stat_ca_root_nss.stat.exists and not stat_cert_pem.stat.exists
