---
- name: "cleanup: clean package cache"
  command:
    cmd: pkg clean -a -y
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: "cleanup: remove ansible directory"
  file:
    path: /root/.ansible
    state: absent
  changed_when: false

- name: "cleanup: remove authorized_key"
  authorized_key:
    user: root
    key: "{{ lookup('file', '../ansible/bsdkit.pub') }}"
    state: absent
  when: bsdkit_ssh_public_key | length > 0
