- name: "Retrieve freebsd_major"
  shell: |
    set -o pipefail
    echo "{{ ansible_distribution_release }}" | sed -E 's/([0-9]+).*/\1/;'
  register: freebsd_major
  changed_when: False

- name: "Check sysctl: security.jail.jailed"
  shell:
    cmd: |
      set -o pipefail
      echo "sysctl -n security.jail.jailed: $(sysctl -n security.jail.jailed)"
      [ $(sysctl -n security.jail.jailed) = '1' ]
  changed_when: False
  ignore_errors: True
  register: sysctl_security_jail_jailed

- name: "Check sysctl: kern.hostuuid matches with bsdkit"
  shell:
    cmd: |
      set -o pipefail
      echo "sysctl -n kern.hostuuid: $(sysctl -n kern.hostuuid)"
      [ $(sysctl -n kern.hostuuid) = '2e158b17-5e10-11e5-ac21-080027af0e2a' ]
  changed_when: False
  ignore_errors: True
  register: sysctl_kern_hostuuid

- name: "set_fact: bsdkit defaults"
  set_fact:
    default_bsdkit_root_url: "https://olgeni.olgeni.com/FreeBSD"
    default_bsdkit_version: "12.2"
    default_bsdkit_arch: "amd64"
    default_bsdkit_tree: "default"
    default_bsdkit_pkgset: "nox11"

- name: "set_fact: bsdkit variables"
  set_fact:
    bsdkit_interface: "{{ lookup('env', 'BSDKIT_INTERFACE') }}"
    bsdkit_ifconfig: "{{ lookup('env', 'BSDKIT_IFCONFIG') }}"
    bsdkit_defaultrouter: "{{ lookup('env', 'BSDKIT_DEFAULTROUTER') }}"
    bsdkit_ssh_public_key: "{{ lookup('env', 'BSDKIT_SSH_PUBLIC_KEY') }}"
    bsdkit_jail_proxy: "{{ lookup('env', 'BSDKIT_JAIL_PROXY') }}"
    bsdkit_root_url: "{{ lookup('env', 'BSDKIT_ROOT_URL') | default(default_bsdkit_root_url, True) }}"
    bsdkit_version: "{{ lookup('env', 'BSDKIT_VERSION') | default(default_bsdkit_version, True) }}"
    bsdkit_arch: "{{ lookup('env', 'BSDKIT_ARCH') | default(default_bsdkit_arch, True) }}"
    bsdkit_tree: "{{ lookup('env', 'BSDKIT_TREE') | default(default_bsdkit_tree, True) }}"
    bsdkit_pkgset: "{{ lookup('env', 'BSDKIT_PKGSET') | default(default_bsdkit_pkgset, True) }}"
    is_host_install: "{{ sysctl_security_jail_jailed is failed or sysctl_kern_hostuuid is succeeded }}"

- name: "debug: bsdkit_interface"
  debug:
    var: bsdkit_interface

- name: "debug: bsdkit_ifconfig"
  debug:
    var: bsdkit_ifconfig

- name: "debug: bsdkit_defaultrouter"
  debug:
    var: bsdkit_defaultrouter

- name: "debug: bsdkit_ssh_public_key"
  debug:
    var: bsdkit_ssh_public_key

- name: "debug: bsdkit_jail_proxy"
  debug:
    var: bsdkit_jail_proxy

- name: "debug: bsdkit_root_url"
  debug:
    var: bsdkit_root_url

- name: "debug: bsdkit_version"
  debug:
    var: bsdkit_version

- name: "debug: bsdkit_arch"
  debug:
    var: bsdkit_arch

- name: "debug: bsdkit_tree"
  debug:
    var: bsdkit_tree

- name: "debug: bsdkit_pkgset"
  debug:
    var: bsdkit_pkgset

- name: "debug: sysctl_kern_hostuuid"
  debug:
    var: sysctl_kern_hostuuid

- name: "debug: sysctl_security_jail_jailed"
  debug:
    var: sysctl_security_jail_jailed

- name: "debug: is_host_install"
  debug:
    var: is_host_install
