- name: "kenv smbios.system.product"
  command:
    cmd: kenv smbios.system.product
  changed_when: no
  ignore_errors: yes
  register: kenv_smbios_system_product

- name: "kenv smbios.bios.vendor"
  command:
    cmd: kenv smbios.bios.vendor
  changed_when: no
  ignore_errors: yes
  register: kenv_smbios_bios_vendor

- name: "Retrieve freebsd_major"
  shell: |
    set -o pipefail
    echo "{{ ansible_distribution_release }}" | sed -E 's/([0-9]+).*/\1/;'
  register: freebsd_major
  changed_when: no

- name: "Check sysctl: security.jail.jailed"
  shell:
    cmd: |
      set -o pipefail
      echo "sysctl -n security.jail.jailed: $(sysctl -n security.jail.jailed)"
      [ $(sysctl -n security.jail.jailed) = '1' ]
  changed_when: no
  ignore_errors: yes
  register: sysctl_security_jail_jailed

- name: "set_fact: bsdkit defaults"
  set_fact:
    default_bsdkit_root_url: "https://olgeni.olgeni.com/FreeBSD"
    default_bsdkit_version: "12.2"
    default_bsdkit_arch: "amd64"
    default_bsdkit_tree: "default"
    default_bsdkit_pkgset: "nox11"

- name: "set_fact: bsdkit variables"
  set_fact:
    bsdkit_interface: "{{ lookup('env', 'BSDKIT_INTERFACE') }}"
    bsdkit_ifconfig: "{{ lookup('env', 'BSDKIT_IFCONFIG') }}"
    bsdkit_defaultrouter: "{{ lookup('env', 'BSDKIT_DEFAULTROUTER') }}"
    bsdkit_ssh_public_key: "{{ lookup('env', 'BSDKIT_SSH_PUBLIC_KEY') }}"
    bsdkit_jail_proxy: "{{ lookup('env', 'BSDKIT_JAIL_PROXY') }}"
    bsdkit_root_url: "{{ lookup('env', 'BSDKIT_ROOT_URL') | default(default_bsdkit_root_url, True) }}"
    bsdkit_version: "{{ lookup('env', 'BSDKIT_VERSION') | default(default_bsdkit_version, True) }}"
    bsdkit_arch: "{{ lookup('env', 'BSDKIT_ARCH') | default(default_bsdkit_arch, True) }}"
    bsdkit_tree: "{{ lookup('env', 'BSDKIT_TREE') | default(default_bsdkit_tree, True) }}"
    bsdkit_pkgset: "{{ lookup('env', 'BSDKIT_PKGSET') | default(default_bsdkit_pkgset, True) }}"
    is_host_install: "{{ sysctl_security_jail_jailed is failed }}"

- name: "Check ZFS boot pool"
  shell:
    cmd: |
      set -o pipefail
      zpool get -H -o name bootfs | head -n1
  register: zpool_get_bootfs
  changed_when: no
  ignore_errors: yes

- name: "set_fact: zfs_enabled"
  set_fact:
    zfs_enabled: "{{ ((zpool_get_bootfs is succeeded) and (zpool_get_bootfs.stdout | length > 0)) | bool }}"

- name: "set_fact: boot_pool"
  set_fact:
    boot_pool: "{{ zpool_get_bootfs.stdout }}"
    when: zfs_enabled | bool

- name: "set_fact: is_droplet"
  set_fact:
    is_droplet: "{{ (is_host_install | bool) and (kenv_smbios_system_product.stdout in ['Droplet']) }}"

- name: "debug: bsdkit_interface"
  debug:
    var: bsdkit_interface

- name: "debug: bsdkit_ifconfig"
  debug:
    var: bsdkit_ifconfig

- name: "debug: bsdkit_defaultrouter"
  debug:
    var: bsdkit_defaultrouter

- name: "debug: bsdkit_ssh_public_key"
  debug:
    var: bsdkit_ssh_public_key

- name: "debug: bsdkit_jail_proxy"
  debug:
    var: bsdkit_jail_proxy

- name: "debug: bsdkit_root_url"
  debug:
    var: bsdkit_root_url

- name: "debug: bsdkit_version"
  debug:
    var: bsdkit_version

- name: "debug: bsdkit_arch"
  debug:
    var: bsdkit_arch

- name: "debug: bsdkit_tree"
  debug:
    var: bsdkit_tree

- name: "debug: bsdkit_pkgset"
  debug:
    var: bsdkit_pkgset

- name: "debug: sysctl_security_jail_jailed"
  debug:
    var: sysctl_security_jail_jailed

- name: "debug: is_host_install"
  debug:
    var: is_host_install

- name: "debug: zpool_get_bootfs"
  debug:
    var: zpool_get_bootfs

- name: "debug: zfs_enabled"
  debug:
    var: zfs_enabled

- name: "debug: boot_pool"
  debug:
    var: boot_pool

- name: "debug: is_droplet"
  debug:
    var: is_droplet
