---
- name: "fscd: stat /usr/local/etc/fscd.conf"
  stat:
    path: /usr/local/etc/fscd.conf
  register: stat_fscd_conf

- name: "fscd: disable service"
  service:
    name: fscd
    enabled: false
    state: stopped
  when: stat_fscd_conf.stat.exists

- name: "fscd: remove /usr/local/etc/fscd.conf"
  file:
    path: /usr/local/etc/fscd.conf
    state: absent
  when: stat_fscd_conf.stat.exists

- name: "fscd: remove 'fscd' package"
  pkgng:
    name:
      - sysutils/fsc
    state: absent
  when: stat_fscd_conf.stat.exists
