---
- name: Read smbios.system.product
  command:
    cmd: kenv smbios.system.product
  changed_when: false
  ignore_errors: true
  register: kenv_smbios_system_product

- name: Read smbios.bios.vendor
  command:
    cmd: kenv smbios.bios.vendor
  changed_when: false
  ignore_errors: true
  register: kenv_smbios_bios_vendor
