---
- name: "login-conf: configure login.conf (check for lang=en_US.UTF-8)"
  command:
    cmd: grep -Fq ':lang=en_US.UTF-8:' /etc/login.conf
  register: login_conf_lang
  changed_when: false
  failed_when: false

- name: "login-conf: configure login.conf (lang=en_US.UTF-8)"
  lineinfile:
    dest: /etc/login.conf
    line: "\t:lang=en_US.UTF-8:\\"
    insertafter: "^default:"
    firstmatch: true
  when: login_conf_lang.rc != 0
  notify: cap_mkdb

- name: "login-conf: configure login.conf (charset=UTF-8)"
  lineinfile:
    dest: /etc/login.conf
    line: "\t:charset=UTF-8:\\"
    insertafter: "^default:"
    firstmatch: true
  when: login_conf_lang.rc != 0
  notify: cap_mkdb

- name: "login-conf: flush handlers"
  meta: flush_handlers
