- name: "mysql-zfs"
  when: zfs_enabled | bool
  block:
    - name: "Check contents of MySQL home directory"
      find:
        paths: "/var/db/mysql"
      register: find_var_db_mysql

    - name: "Create ZFS dataset for MySQL"
      zfs:
        name: "{{ boot_pool }}/var/db/mysql"
        state: present
        extra_zfs_properties:
          canmount: on
      when: find_var_db_mysql.matched == 0
