- name: "mysql-zfs"
  when: zfs_enabled | bool
  block:
    - name: "Check contents of MySQL home directory"
      find:
        paths: "/var/db/mysql"
        recurse: True
        hidden: True
      register: find_var_db_mysql

    - name: Gather facts about MySQL ZFS dataset
      zfs_facts:
        dataset: "{{ boot_pool }}/var/db/mysql"
      ignore_errors: True
      register: mysql_zfs_facts

    - name: "Create ZFS dataset for MySQL"
      zfs:
        name: "{{ boot_pool }}/var/db/mysql"
        state: present
        extra_zfs_properties:
          canmount: on
          compression: lz4
          atime: off
          redundant_metadata: most
      when: find_var_db_mysql.matched == 0 or mysql_zfs_facts is successful
