- name: "Create /usr/local/etc/newsyslog.conf.d/"
  file:
    path: /usr/local/etc/newsyslog.conf.d/
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: "Remove obsolete newsyslog files (newsyslog.conf)"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/newsyslog.conf.d/newsyslog.conf
    - /usr/local/etc/newsyslog.conf.d/bsdkit.conf

- name: "Install newsyslog files"
  copy:
    src: "{{ item }}"
    dest: /usr/local/etc/newsyslog.conf.d/
    owner: root
    group: wheel
    mode: "0644"
  with_fileglob:
    - ../ansible/newsyslog.conf.d/*.conf
