- name: "periodic: configure periodic.conf"
  lineinfile:
    dest: /etc/periodic.conf
    line: "{{ item.key }}=\"{{ item.value }}\""
    regexp: "^{{ item.key }} *="
    create: yes
    mode: "0644"
  with_items: "{{ periodic_conf | dict2items }}"
