- name: "postgres-zfs: block ZFS"
  when: zfs_enabled | bool
  block:
    - name: "postgres-zfs: check contents of PostgreSQL home directory"
      find:
        paths: "/var/db/postgres"
        recurse: yes
        hidden: yes
      register: find_var_db_postgres

    - name: "postgres-zfs: gather facts about PostgreSQL ZFS dataset"
      zfs_facts:
        dataset: "{{ boot_pool }}/var/db/postgres"
      ignore_errors: yes
      register: var_db_postgres_zfs_facts

    - name: "postgres-zfs: create ZFS dataset for PostgreSQL"
      zfs:
        name: "{{ boot_pool }}/var/db/postgres"
        state: present
        extra_zfs_properties:
          canmount: on
          compression: "{{ zfs_compression }}"
          atime: off
          redundant_metadata: most
      when: find_var_db_postgres.matched == 0 or var_db_postgres_zfs_facts is successful
