- name: "postgres-zfs"
  when: zfs_enabled | bool
  block:
    - name: "Check contents of PostgreSQL home directory"
      find:
        paths: "/var/db/postgres"
      register: find_var_db_postgres

    - name: "Create ZFS dataset for PostgreSQL"
      zfs:
        name: "{{ boot_pool }}/var/db/postgres"
        state: present
        extra_zfs_properties:
          canmount: on
      when: find_var_db_postgres.matched == 0
