- name: "Block: ZFS (PostgreSQL)"
  when: zfs_enabled | bool
  block:
    - name: "Check contents of PostgreSQL home directory"
      find:
        paths: "/var/db/postgres"
        recurse: yes
        hidden: yes
      register: find_var_db_postgres

    - name: "Gather facts about PostgreSQL ZFS dataset"
      zfs_facts:
        dataset: "{{ boot_pool }}/var/db/postgres"
      ignore_errors: yes
      register: postgres_zfs_facts

    - name: "Create ZFS dataset for PostgreSQL"
      zfs:
        name: "{{ boot_pool }}/var/db/postgres"
        state: present
        extra_zfs_properties:
          canmount: on
          compression: lz4
          atime: off
          redundant_metadata: most
      when: find_var_db_postgres.matched == 0 or postgres_zfs_facts is successful
