- name: "postgres-zfs"
  when: has_zfs
  block:
    - name: "Check contents of PostgreSQL home directory"
      find:
        paths: "/var/db/postgres"
      register: find_var_db_postgres

    - name: "Create zfs dataset for PostgreSQL"
      zfs:
        name: "{{ zpool_list.stdout }}/var/db/postgres"
        state: present
        extra_zfs_properties:
          canmount: on
          recordsize: 8K
          logbias: throughput
      when: find_var_db_postgres.matched == 0
