- name: "postgres-zfs"
  when: has_zfs | bool
  block:
    - name: "Check contents of PostgreSQL home directory"
      find:
        paths: "/var/db/postgres"
      register: find_var_db_postgres

    - name: "Create zfs dataset for PostgreSQL"
      zfs:
        name: "{{ boot_pool.stdout }}/var/db/postgres"
        state: present
        extra_zfs_properties:
          canmount: on
      when: find_var_db_postgres.matched == 0
