- name: "Create /usr/local/etc/sv"
  file:
    path: /usr/local/etc/sv
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: "Create /var/service"
  file:
    path: /var/service
    state: directory
    owner: root
    group: wheel
    mode: "0755"
