- name: "Check if /vagrant exists"
  stat:
    path: /vagrant
  register: stat_vagrant

- name: "Enable sudo for vagrant user"
  copy:
    content: "vagrant ALL = (ALL) NOPASSWD: SETENV: ALL"
    dest: /usr/local/etc/sudoers.d/vagrant
  when: stat_vagrant.stat.isdir is defined and stat_vagrant.stat.isdir
