- name: "VirtualBox configuration"
  lineinfile:
    dest: /etc/rc.conf
    line: '{{ item }}_enable="YES"'
    regexp: "^{{ item }}_enable"
    insertafter: EOF
  with_items:
    - vboxguest
    - vboxservice
  when: platform_is_virtualbox | bool
