- name: "zfs: block"
  when: zfs_enabled | bool
  block:
    - name: "zfs: create ZFS dataset for /var/db"
      zfs:
        name: "{{ boot_pool }}/var/db"
        state: present
        extra_zfs_properties:
          canmount: off

    - name: "zfs: create ZFS dataset for /jails"
      zfs:
        name: "{{ boot_pool }}/jails"
        state: present

    - name: "zfs: create ZFS dataset for /usr/local"
      zfs:
        name: "{{ boot_pool }}/usr/local"
        state: present
        extra_zfs_properties:
          canmount: off

    - name: "zfs: gather facts about pkg ZFS dataset"
      zfs_facts:
        dataset: "{{ boot_pool }}/usr/local/pkg"
      ignore_errors: yes
      register: zfs_facts_usr_local_pkg

    - name: "zfs: remove usr/local/pkg"
      when: zfs_facts_usr_local_pkg is successful
      block:
        - name: "zfs: save /var/db/pkg"
          shell: |
            set -e -u -o pipefail
            mkdir /tmp/pkg/
            mv /var/db/pkg/* /tmp/pkg/

        - name: "zfs: destroy ZFS dataset for pkg"
          zfs:
            name: "{{ boot_pool }}/usr/local/pkg"
            state: absent

        - name: "zfs: restore /var/db/pkg"
          shell: |
            set -e -u -o pipefail
            mkdir -p /usr/local/pkg
            rm -r -f /var/db/pkg
            ln -s -f /usr/local/pkg /var/db/pkg
            mv /tmp/pkg/* /var/db/pkg/
            rmdir /tmp/pkg
