- name: "Create zfs dataset for /var/db"
  zfs:
    name: "{{ boot_pool }}/var/db"
    state: present
    extra_zfs_properties:
      canmount: off
  when: zfs_enabled | bool

- name: "Create ZFS dataset for /jails"
  zfs:
    name: "{{ boot_pool }}/jails"
    state: present
  when: zfs_enabled | bool

