- name: "Run tzsetup (stat: /var/db/zoneinfo)"
  stat:
    path: /var/db/zoneinfo
  register: stat_zoneinfo

- name: "Run tzsetup (exec)"
  command:
    cmd: tzsetup Europe/Rome
  when: not stat_zoneinfo.stat.exists
