- name: "Check ZFS boot pool"
  shell:
    cmd: |
      set -o pipefail
      zpool get -H -o name bootfs | head -n1
  register: zpool_get_bootfs
  changed_when: no
  ignore_errors: yes

- name: "set_fact: zfs_enabled"
  set_fact:
    zfs_enabled: "{{ ((zpool_get_bootfs is succeeded) and (zpool_get_bootfs.stdout | length > 0)) | bool }}"

- name: "set_fact: boot_pool"
  set_fact:
    boot_pool: "{{ zpool_get_bootfs.stdout }}"
    when: zfs_enabled | bool

- name: "debug: zpool_get_bootfs"
  debug:
    var: zpool_get_bootfs

- name: "debug: zfs_enabled"
  debug:
    var: zfs_enabled

- name: "debug: boot_pool"
  debug:
    var: boot_pool
