- name: "Check zpool list"
  shell:
    cmd: |
      set -o pipefail
      zpool list -H -o name | head -n1
  register: zpool_list
  changed_when: False

- name: "set_fact: has_zfs"
  set_fact:
    has_zfs: "{{ ((zpool_list is succeeded) and (zpool_list.stdout | length > 0)) | bool }}"

- name: "set_fact: zpool"
  set_fact:
    zpool: "{{ zpool_list.stdout }}"
    when: has_zfs
