- name: "Check zpool list"
  shell:
    cmd: |
      set -o pipefail
      kenv zfs_be_root | cut -d/ -f1
  register: boot_pool
  changed_when: False

- name: "set_fact: has_zfs"
  set_fact:
    has_zfs: "{{ ((boot_pool is succeeded) and (boot_pool.stdout | length > 0)) | bool }}"

- name: "set_fact: zpool"
  set_fact:
    zpool: "{{ boot_pool.stdout }}"
    when: has_zfs
