- name: "Check ZFS boot pool"
  shell:
    cmd: |
      set -o pipefail
      zpool get -H -o name bootfs | head -n1
  register: boot_pool
  changed_when: False
  ignore_errors: True

- name: "set_fact: has_zfs"
  set_fact:
    has_zfs: "{{ ((boot_pool is succeeded) and (boot_pool.stdout | length > 0)) | bool }}"

- name: "set_fact: zpool"
  set_fact:
    zpool: "{{ boot_pool.stdout }}"
    when: has_zfs | bool

- name: "debug: boot_pool"
  debug:
    var: boot_pool

- name: "debug: has_zfs"
  debug:
    var: has_zfs

- name: "debug: zpool"
  debug:
    var: zpool
