#!/bin/sh

# 75729d6d-6cc9-11ec-922a-4c526214c986

set -o errexit -o nounset -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(grep -v '^\s*#' envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(grep -v '^\s*#' envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/* | grep -v '^\s*#')"
fi

ENV_ARGS=""
if [ -n "${ENVRC}" ]; then
    ENV_ARGS="-S \"${ENVRC}\""
fi

: ${PYTHON_USER:="nobody"}
: ${PYTHON_GROUP:="nobody"}
: ${PYTHON_HOME:="$(eval echo ~${PYTHON_USER})"}
: ${PYTHON_PATH:=""}
: ${PYTHON_VENV:="${PYTHON_PATH}/.venv"}
: ${PYTHON_EXECUTABLE:="python"}
: ${PYTHON_ARGS=""}
: ${PYTHON_FILE:="main.py"}
: ${PYTHON_UV:=""}

cd ${PYTHON_PATH}

export OSTYPE=freebsd

. ${PYTHON_VENV}/bin/activate

if [ "$(id -u)" = "0" ]; then
    CHPST_COMMAND="chpst -u ${PYTHON_USER}:${PYTHON_GROUP} ${CHPST_ARGS}"
fi

PYTHON_PREFIX=""
if [ -n "${PYTHON_UV}" ]; then
    PYTHON_PREFIX="uv run "
fi

exec env ${ENV_ARGS} HOME="${PYTHON_HOME}" PYTHONUNBUFFERED=1 PYTHONPATH="${PYTHON_PATH}" ${CHPST_COMMAND} ${PYTHON_PREFIX}"${PYTHON_EXECUTABLE}" ${PYTHON_ARGS} "${PYTHON_FILE}"
