#!/bin/sh

# 75729d6d-6cc9-11ec-922a-4c526214c986

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/*)"
fi

: ${PYTHON_USER:="nobody"}
: ${PYTHON_PATH:=""}
: ${PYTHON_ARGS=""}
: ${PYTHON_VENV:="${PYTHON_PATH}/.venv"}
: ${PYTHON_FILE:="main.py"}
: ${PYTHON_EXECUTABLE:="python"}

cd ${PYTHON_PATH}

. ${PYTHON_VENV}/bin/activate

if [ "$(id -u)" = "0" ]; then
    CHPST_COMMAND="chpst -u ${PYTHON_USER} ${CHPST_ARGS}"
fi

exec env -S "${ENVRC}" PYTHONUNBUFFERED=1 PYTHONPATH=${PYTHON_PATH} ${CHPST_COMMAND} ${PYTHON_EXECUTABLE} ${PYTHON_ARGS} ${PYTHON_FILE}
