#!/bin/sh

# 75729d6d-6cc9-11ec-922a-4c526214c986

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . $(realpath config)

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC}$(cat envrc.local)"
fi

: ${PYTHON_USER:="nobody"}
: ${PYTHON_PATH:=""}
: ${PYTHON_ARGS=""}
: ${PYTHON_VENV:="${PYTHON_PATH}/.venv"}
: ${PYTHON_FILE:="main.py"}
: ${PYTHON_EXECUTABLE:="python"}

cd ${PYTHON_PATH}

. ${PYTHON_VENV}/bin/activate

exec env -S "${ENVRC}" chpst -u ${PYTHON_USER} ${CHPST_ARGS} ${PYTHON_EXECUTABLE} ${PYTHON_ARGS} ${PYTHON_FILE}
