---
- name: Add Vault group
  group:
    name: vault
    gid: "{{ vault_user_gid }}"
    state: present

- name: Add Vault user
  user:
    name: vault
    uid: "{{ vault_user_uid }}"
    group: vault
    home: /var/db/vault
    shell: /bin/sh
    comment: "Vault Daemon"
    state: present

- name: Create data directory for Vault
  file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: vault
    group: vault
  with_items:
    - /var/db/vault
