#!/bin/sh

# B41FC276-D139-405E-A31E-16940C01A972

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . $(realpath config)

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/*)"
fi

: ${NATS_DATA_DIR:="/var/db/nats"}
: ${NATS_USER:="nats"}
: ${NATS_GROUP:="nats"}
: ${NATS_ARGS="-c nats.conf"}
: ${NATS_CERT_FILE:=""} # /usr/local/etc/letsencrypt/live/FQDN/fullchain.pem
: ${NATS_KEY_FILE:=""}  # /usr/local/etc/letsencrypt/live/FQDN/privkey.pem

mkdir -p ${NATS_DATA_DIR}/certs

NATS_CERTS_DIR="${NATS_DATA_DIR}/certs"

chown -R ${NATS_USER}:${NATS_GROUP} ${NATS_DATA_DIR}

if [ -n "${NATS_CERT_FILE}" ]; then
    install -m 644 -o nats -g nats "${NATS_CERT_FILE}" "${NATS_CERTS_DIR}/cert.pem"
fi

if [ -n "${NATS_KEY_FILE}" ]; then
    install -m 600 -o nats -g nats "${NATS_KEY_FILE}" "${NATS_CERTS_DIR}/key.pem"
fi

exec env -S "${ENVRC}" chpst -u ${NATS_USER}:${NATS_GROUP} ${CHPST_ARGS} /usr/local/bin/nats-server ${NATS_ARGS}
