---
- name: Load bsdkit-defaults.yml
  tags:
    - always
  include_vars:
    file: bsdkit-defaults.yml

- name: Check if /.bsdkit.yml exists
  tags:
    - always
  stat:
    path: /.bsdkit.yml
  register: bsdkit_yml

- name: Move /.bsdkit.yml to /usr/local/etc/bsdkit.yml
  when: bsdkit_yml.stat.exists
  tags:
    - always
  block:
    - name: Copy /.bsdkit.yml to /usr/local/etc/bsdkit.yml
      copy:
        src: /.bsdkit.yml
        dest: /usr/local/etc/bsdkit.yml
        remote_src: yes
        owner: root
        group: wheel
        mode: "0600"

    - name: Remove /.bsdkit.yml
      file:
        path: /.bsdkit.yml
        state: absent

- name: Check if /usr/local/etc/bsdkit.yml exists
  tags:
    - always
  stat:
    path: /usr/local/etc/bsdkit.yml
  register: bsdkit_yml

- name: Load /usr/local/etc/bsdkit.yml
  when: bsdkit_yml.stat.exists
  tags:
    - always
  include_vars:
    file: /usr/local/etc/bsdkit.yml

- name: Create /usr/local/etc/bsdkit.yml
  when: not bsdkit_yml.stat.exists
  tags:
    - always
  copy:
    src: bsdkit-defaults.yml
    dest: /usr/local/etc/bsdkit.yml
    owner: root
    group: wheel
    mode: "0600"

- name: Set root shell
  tags:
    - configure
  user:
    name: root
    shell: /bin/csh
