---
- name: Load bsdkit-defaults.yml
  include_vars:
    file: bsdkit-defaults.yml

- name: Check if /.bsdkit.yml exists
  stat:
    path: /.bsdkit.yml
  register: stat_root_bsdkit_yml

- name: Move /.bsdkit.yml to /usr/local/etc/bsdkit.yml
  when: stat_root_bsdkit_yml.stat.exists
  block:
    - name: Copy /.bsdkit.yml to /usr/local/etc/bsdkit.yml
      copy:
        src: /.bsdkit.yml
        dest: /usr/local/etc/bsdkit.yml
        remote_src: true
        owner: root
        group: wheel
        mode: "0600"

    - name: Remove /.bsdkit.yml
      file:
        path: /.bsdkit.yml
        state: absent

- name: Copy facts from ansible_local.bsdkit to bsdkit
  when: ansible_local is defined and ansible_local.bsdkit is defined
  set_fact:
    bsdkit: "{{ ansible_local.bsdkit }}"
