---
- name: Add Consul group
  group:
    name: consul
    gid: 469
    state: present

- name: Add Consul user
  user:
    name: consul
    uid: 469
    group: consul
    home: /var/db/consul
    shell: /bin/sh
    comment: "Consul Daemon"
    state: present

- name: Create data directory for Consul
  file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: consul
    group: consul
  with_items:
    - /var/db/consul

- name: Create /usr/local/etc/rc.conf.d/consul
  copy:
    dest: /usr/local/etc/rc.conf.d/consul
    content: |
      consul_datadir=/var/db/consul
    owner: root
    group: wheel
    mode: 0644
