---
- name: Install packages (nats-server)
  community.general.pkgng:
    name: "{{ item }}"
    state: present
  loop:
    - net/nats-nkeys
    - net/nats-nsc
    - net/nats-server
    - net/natscli

- name: Create /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}
  file:
    mode: "0755"
    path: /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}
    state: directory

- name: Create /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}/data
  file:
    mode: "0755"
    path: /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}/data
    state: directory

- name: Copy NATS configuration files
  template:
    src: "{{ item }}"
    dest: "/var/db/runit/{{ bsdkit_sv_nats_server_service_name }}/{{ item | basename }}"
    group: wheel
    mode: "0644"
  with_items: "{{ bsdkit_sv_nats_server_configuration }}"
  notify:
    - restart_sv_nats_server

- name: Copy /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}/run
  copy:
    dest: /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}/run
    group: wheel
    src: ../files/run
    mode: "0755"
  notify:
    - restart_sv_nats_server

- name: Copy /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}/nats.conf.sample
  copy:
    dest: /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}/nats.conf.sample
    group: wheel
    src: ../files/nats.conf.sample
    mode: "0644"
  notify:
    - restart_sv_nats_server

- name: Link /var/service/{{ bsdkit_sv_nats_server_service_name }}
  file:
    src: /var/db/runit/{{ bsdkit_sv_nats_server_service_name }}
    path: /var/service/{{ bsdkit_sv_nats_server_service_name }}
    state: link
  notify:
    - restart_sv_nats_server
