---
- name: "facts: register kenv smbios.system.product"
  command:
    cmd: kenv smbios.system.product
  changed_when: false
  ignore_errors: true
  register: kenv_smbios_system_product

# - name: "facts: debug kenv_smbios_system_product"
#   debug:
#     var: kenv_smbios_system_product

- name: "facts: register kenv smbios.bios.vendor"
  command:
    cmd: kenv smbios.bios.vendor
  changed_when: false
  ignore_errors: true
  register: kenv_smbios_bios_vendor

# - name: "facts: debug kenv_smbios_bios_vendor"
#   debug:
#     var: kenv_smbios_bios_vendor

- name: "facts: register freebsd_major"
  shell:
    cmd: |
      set -o pipefail
      echo "{{ ansible_distribution_release }}" | sed -E 's/([0-9]+).*/\1/;'
  register: freebsd_major
  changed_when: false

# - name: "facts: debug freebsd_major"
#   debug:
#     var: freebsd_major

- name: "facts: register security.jail.jailed"
  shell:
    cmd: |
      set -o pipefail
      sysctl -n security.jail.jailed
  changed_when: false
  register: sysctl_security_jail_jailed

# - name: "facts: debug sysctl_security_jail_jailed"
#   debug:
#     var: sysctl_security_jail_jailed

- name: "facts: set_fact (security_jail_jailed)"
  set_fact:
    security_jail_jailed: "{{ sysctl_security_jail_jailed.stdout == '1' }}"

# - name: "facts: debug security_jail_jailed"
#   debug:
#     var: security_jail_jailed

- name: "facts: set_fact (bsdkit defaults)"
  set_fact:
    default_bsdkit_root_url: https://hub.olgeni.com/FreeBSD
    default_bsdkit_version: "13.1"
    default_bsdkit_arch: amd64
    default_bsdkit_tree: default
    default_bsdkit_pkgset: nox11
    default_bsdkit_chroot: false

- name: "facts: set_fact (bsdkit variables)"
  set_fact:
    bsdkit_interface: "{{ lookup('env', 'BSDKIT_INTERFACE') }}"
    bsdkit_ifconfig: "{{ lookup('env', 'BSDKIT_IFCONFIG') }}"
    bsdkit_defaultrouter: "{{ lookup('env', 'BSDKIT_DEFAULTROUTER') }}"
    bsdkit_ssh_public_key: "{{ lookup('env', 'BSDKIT_SSH_PUBLIC_KEY') }}"
    bsdkit_jail_proxy: "{{ lookup('env', 'BSDKIT_JAIL_PROXY') }}"
    bsdkit_root_url: "{{ lookup('env', 'BSDKIT_ROOT_URL') | default(default_bsdkit_root_url, True) }}"
    bsdkit_version: "{{ lookup('env', 'BSDKIT_VERSION') | default(default_bsdkit_version, True) }}"
    bsdkit_arch: "{{ lookup('env', 'BSDKIT_ARCH') | default(default_bsdkit_arch, True) }}"
    bsdkit_tree: "{{ lookup('env', 'BSDKIT_TREE') | default(default_bsdkit_tree, True) }}"
    bsdkit_pkgset: "{{ lookup('env', 'BSDKIT_PKGSET') | default(default_bsdkit_pkgset, True) }}"
    bsdkit_chroot: "{{ (lookup('env', 'BSDKIT_CHROOT') | default(default_bsdkit_chroot, False)) | bool }}"

# - name: "facts: debug bsdkit_interface"
#   debug:
#     var: bsdkit_interface

# - name: "facts: debug bsdkit_ifconfig"
#   debug:
#     var: bsdkit_ifconfig

# - name: "facts: debug bsdkit_defaultrouter"
#   debug:
#     var: bsdkit_defaultrouter

# - name: "facts: debug bsdkit_ssh_public_key"
#   debug:
#     var: bsdkit_ssh_public_key

# - name: "facts: debug bsdkit_jail_proxy"
#   debug:
#     var: bsdkit_jail_proxy

# - name: "facts: debug bsdkit_root_url"
#   debug:
#     var: bsdkit_root_url

# - name: "facts: debug bsdkit_version"
#   debug:
#     var: bsdkit_version

# - name: "facts: debug bsdkit_arch"
#   debug:
#     var: bsdkit_arch

# - name: "facts: debug bsdkit_tree"
#   debug:
#     var: bsdkit_tree

# - name: "facts: debug bsdkit_pkgset"
#   debug:
#     var: bsdkit_pkgset

# - name: "facts: debug bsdkit_chroot"
#   debug:
#     var: bsdkit_chroot

- name: "facts: set_fact (is_host_install)"
  set_fact:
    is_host_install: "{{ not security_jail_jailed }}"

# - name: "facts: debug is_host_install"
#   debug:
#     var: is_host_install

- name: "facts: set_fact (is_jail_install)"
  set_fact:
    is_jail_install: "{{ security_jail_jailed }}"

# - name: "facts: debug is_jail_install"
#   debug:
#     var: is_jail_install

- name: "facts: set_fact (is_chroot_install)"
  set_fact:
    is_chroot_install: "{{ bsdkit_chroot }}"

# - name: "facts: debug is_chroot_install"
#   debug:
#     var: is_chroot_install

- name: "facts: register uname -K"
  command:
    cmd: |
      uname -K
  register: uname_k_output
  changed_when: false

# - name: "facts: debug uname_k_output"
#   debug:
#     var: uname_k_output

- name: "facts: set_fact (uname_k)"
  set_fact:
    uname_k: "{{ uname_k_output.stdout }}"

# - name: "facts: debug uname_k"
#   debug:
#     var: uname_k

- name: "facts: set_fact (zfs_compression, default)"
  set_fact:
    zfs_compression: lz4

- name: "facts: set_fact (zfs_compression, zstd)"
  when: uname_k | int > 1300000
  set_fact:
    zfs_compression: zstd

# - name: "facts: debug zfs_compression"
#   debug:
#     var: zfs_compression

- name: "facts: check ZFS boot pool"
  shell:
    cmd: |
      set -o pipefail
      zpool get -H -o name,value bootfs | awk '$2 != "-" { print $1 }'
  register: zpool_get_bootfs
  changed_when: false
  ignore_errors: true

# - name: "facts: debug zpool_get_bootfs"
#   debug:
#     var: zpool_get_bootfs

- name: "facts: set_fact zfs_available"
  set_fact:
    zfs_available: "{{ ((zpool_get_bootfs is succeeded) and (zpool_get_bootfs.stdout | length > 0)) | bool }}"

# - name: "facts: debug zfs_available"
#   debug:
#     var: zfs_available

- name: "facts: set_fact boot_pool"
  when: zfs_available
  set_fact:
    boot_pool: "{{ zpool_get_bootfs.stdout }}"

# - name: "facts: debug boot_pool"
#   debug:
#     var: boot_pool

- name: "facts: set_fact platform_is_digitalocean"
  set_fact:
    platform_is_digitalocean: "{{ (is_host_install | bool) and (kenv_smbios_system_product.stdout in ['Droplet']) }}"

# - name: "facts: debug platform_is_digitalocean"
#   debug:
#     var: platform_is_digitalocean

- name: "facts: set_fact platform_is_virtualbox"
  set_fact:
    platform_is_virtualbox: "{{ kenv_smbios_system_product.stdout == 'VirtualBox' }}"

- name: "facts: set_fact platform_is_vmware"
  set_fact:
    platform_is_vmware: "{{ kenv_smbios_system_product.stdout == 'VMware Virtual Platform' }}"

- name: "facts: register netstat output"
  shell:
    cmd: |
      set -o pipefail
      netstat --libxo json -n -r
  register: netstat_r_output
  changed_when: false

- name: "facts: register gateway information"
  shell:
    cmd: |
      set -o pipefail
      cat << EOF | jq -r '.["statistics"]["route-information"]["route-table"]["rt-family"][] | select(.["address-family"] == "Internet") | .["rt-entry"][] | select(.["destination"] == "default") | { interface: .["interface-name"], address: .["gateway"] }'
      {{ netstat_r_output.stdout }}
      EOF
  register: gateway_data_result
  changed_when: false

- name: "facts: set_fact gateway_data"
  set_fact:
    gateway_data: "{{ gateway_data_result.stdout | from_json }}"
