#!/bin/sh

# b41fc276-d139-405e-a31e-16940c01a972

set -o errexit -o nounset -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/*)"
fi

: ${NATS_DATA_DIR:="/var/db/nats"}
: ${NATS_USER:="nats"}
: ${NATS_GROUP:="nats"}
: ${NATS_ARGS="-c nats.conf"}
: ${NATS_CERT_FILE:=""} # /usr/local/etc/letsencrypt/live/FQDN/fullchain.pem
: ${NATS_KEY_FILE:=""}  # /usr/local/etc/letsencrypt/live/FQDN/privkey.pem

if [ -n "${NATS_CERT_FILE}" ] && ! echo "${NATS_CERT_FILE}" | grep -q "/" > /dev/null; then
    NATS_CERT_FILE="/usr/local/etc/letsencrypt/live/${NATS_CERT_FILE}/fullchain.pem"
fi

if [ -n "${NATS_KEY_FILE}" ] && ! echo "${NATS_KEY_FILE}" | grep -q "/" > /dev/null; then
    NATS_KEY_FILE="/usr/local/etc/letsencrypt/live/${NATS_KEY_FILE}/privkey.pem"
fi

if [ -n "${NATS_CERT_FILE}" ] && [ -n "${NATS_KEY_FILE}" ]; then
    NATS_CERTS_DIR="${NATS_DATA_DIR}/certs"

    mkdir -p ${NATS_CERTS_DIR}

    install -m 644 -o ${NATS_USER} -g ${NATS_GROUP} "${NATS_CERT_FILE}" "${NATS_CERTS_DIR}/cert.pem"
    install -m 600 -o ${NATS_USER} -g ${NATS_GROUP} "${NATS_KEY_FILE}" "${NATS_CERTS_DIR}/key.pem"
fi

chown -R ${NATS_USER}:${NATS_GROUP} ${NATS_DATA_DIR}

if [ -n "${ENVRC}" ]; then
    exec env -S "${ENVRC}" chpst -u ${NATS_USER}:${NATS_GROUP} ${CHPST_ARGS} /usr/local/bin/nats-server ${NATS_ARGS}
else
    exec chpst -u ${NATS_USER}:${NATS_GROUP} ${CHPST_ARGS} /usr/local/bin/nats-server ${NATS_ARGS}
fi
