#!/usr/bin/env zsh

setopt errreturn nounset pipefail

SCRIPT_PATH="$(dirname $(realpath $0))"
SCRIPT_NAME="$(basename $0)"

source ${SCRIPT_PATH}/../lib/colors.inc.sh
source ${SCRIPT_PATH}/../lib/hr-to-bytes.inc.sh
source ${SCRIPT_PATH}/../lib/is-yes.inc.sh
source ${SCRIPT_PATH}/../lib/yaml.inc.sh

if [ "$(uname -s)" != "FreeBSD" ]; then
    error "Must be executed on FreeBSD."
    exit 1
fi

BSDKIT_PATH="$(realpath ${SCRIPT_PATH}/../)"

if [ -x /usr/local/bin/vim ]; then
    export EDITOR=/usr/local/bin/vim
fi

# ===========================================================================

DEFAULT_VERSION=14
DEFAULT_ARCH=amd64

unset POSIXLY_CORRECT

if [ $(whoami) != "root" ]; then
    error "Must be executed as root."
    exit 1
fi

if [ $# -eq 0 ]; then
    cat << EOF

usage: ${SCRIPT_NAME} [option] ...

Options and arguments:

    -v version
    -a arch
    -j jobs
    -P: build images with packages
    -R: build release
    -S: build staging
    -I: build ISO image
    -U: build USB image
    -A: build release/staging/ISO/USB

EOF
fi

_version=${DEFAULT_VERSION}
_arch=${DEFAULT_ARCH}
_jobs_option=""
_with_packages=""

_build_release=""
_build_staging=""
_build_iso=""
_build_usb=""

OPTIND=1
while getopts "v:a:j:PRSIUA" OPT; do
    case ${OPT} in
        v)
            _version="${OPTARG}"
            ;;
        a)
            _arch="${OPTARG}"
            ;;
        j)
            _jobs_option="-j${OPTARG}"
            ;;
        P)
            _with_packages="YES"
            ;;
        R)
            _build_release="YES"
            ;;
        S)
            _build_staging="YES"
            ;;
        I)
            _build_iso="YES"
            ;;
        U)
            _build_usb="YES"
            ;;
        A)
            _build_release="YES"
            _build_staging="YES"
            _build_iso="YES"
            _build_usb="YES"
            ;;
        *) ;;
    esac
done

shift $((OPTIND - 1))

# ===

OS_SRCDIR=${BSDKIT_DATA}/src/${_version}/src

if [ ! -d "${OS_SRCDIR}" ]; then
    error "Source directory not found: ${OS_SRCDIR}"
    exit 1
fi

OS_RELDIR=${BSDKIT_DATA}/src/${_version}/release-${_arch}
OS_REPODIR=${BSDKIT_DATA}/pkgbase

OS_MAJOR=$(get-major-version-from-source ${OS_SRCDIR})
OS_MINOR=$(get-minor-version-from-source ${OS_SRCDIR})
OS_PATCH=$(get-patch-version-from-source ${OS_SRCDIR})

# ===

build-release() {
    local _make_conf=${BSDKIT_PATH}/etc/make.conf
    local _src_conf=${BSDKIT_PATH}/etc/src.conf

    install -o root -g wheel -m 644 ansible/BSDKIT-${_version}-${_arch} ${OS_SRCDIR}/sys/${_arch}/conf/BSDKIT

    KERNCONF="BSDKIT"

    message ">>> Start of build: $(date "+%Y-%m-%d %H:%M:%S")"

    env -i make -s -C ${OS_SRCDIR} \
        __MAKE_CONF=${_make_conf} SRCCONF=${_src_conf} TARGET=${_arch} TARGET_ARCH=${_arch} KERNCONF="${KERNCONF}" \
        ${_jobs_option} buildworld buildkernel

    env -i make -s -C ${OS_SRCDIR}/release \
        __MAKE_CONF=${_make_conf} SRCCONF=${_src_conf} TARGET=${_arch} TARGET_ARCH=${_arch} KERNCONF="${KERNCONF}" \
        release NOPORTS="YES"

    rm -r -f ${OS_RELDIR}
    mkdir -p ${OS_RELDIR}

    env -i make -s -C ${OS_SRCDIR}/release \
        __MAKE_CONF=${_make_conf} SRCCONF=${_src_conf} TARGET=${_arch} TARGET_ARCH=${_arch} KERNCONF="${KERNCONF}" \
        install DESTDIR=${OS_RELDIR}

    ${BSDKIT_PATH}/bsdkit get-src-release-name ${OS_SRCDIR} > ${OS_RELDIR}/ftp/RELEASE

    etcupdate build -s ${OS_SRCDIR} ${OS_RELDIR}/ftp/etcupdate.tar.bz2

    echo -n > ${OS_RELDIR}/ftp/OLDFILES

    env -i make -s -C ${OS_SRCDIR} list-old-files | sed 's/^/old-files: /' >> ${OS_RELDIR}/ftp/OLDFILES
    env -i make -s -C ${OS_SRCDIR} list-old-dirs | sed 's/^/old-dirs: /' >> ${OS_RELDIR}/ftp/OLDFILES
    env -i make -s -C ${OS_SRCDIR} list-old-libs | sed 's/^/old-libs: /' >> ${OS_RELDIR}/ftp/OLDFILES

    env -i make -s -C ${OS_SRCDIR}/release \
        __MAKE_CONF=${_make_conf} SRCCONF=${_src_conf} TARGET=${_arch} TARGET_ARCH=${_arch} KERNCONF="${KERNCONF}" \
        clean

    message ">>> End of build: $(date "+%Y-%m-%d %H:%M:%S")"

    rm -f ${OS_SRCDIR}/sys/${_arch}/conf/BSDKIT
}

get-major-version-from-source() {
    local _src_dir=$1

    if [ ! -d "${_src_dir}" ]; then
        error "Source directory not found: ${_src_dir}"
        return 1
    fi

    local _newvers_sh=${_src_dir}/sys/conf/newvers.sh

    if [ ! -f "${_newvers_sh}" ]; then
        error "newvers.sh not found: ${_newvers_sh}"
        return 1
    fi

    local _revision

    while IFS= read -r line; do
        case "$line" in
            REVISION=*)
                _revision="${line#REVISION=\"}"
                _revision="${_revision%\"}"
                ;;
        esac
    done < <(grep -E '^REVISION=' "$_newvers_sh")

    local major_version="${_revision%%.*}"

    echo "${major_version}"
}

get-minor-version-from-source() {
    local _src_dir=$1

    if [ ! -d "${_src_dir}" ]; then
        error "Source directory not found: ${_src_dir}"
        return 1
    fi

    local _newvers_sh=${_src_dir}/sys/conf/newvers.sh

    if [ ! -f "${_newvers_sh}" ]; then
        error "newvers.sh not found: ${_newvers_sh}"
        return 1
    fi

    local _revision

    while IFS= read -r line; do
        case "$line" in
            REVISION=*)
                _revision="${line#REVISION=\"}"
                _revision="${_revision%\"}"
                ;;
        esac
    done < <(grep -E '^REVISION=' "$_newvers_sh")

    echo "${_revision}"
}

get-patch-version-from-source() {
    local _src_dir=$1

    if [ ! -d "${_src_dir}" ]; then
        error "Source directory not found: ${_src_dir}"
        return 1
    fi

    local _newvers_sh=${_src_dir}/sys/conf/newvers.sh

    if [ ! -f "${_newvers_sh}" ]; then
        error "newvers.sh not found: ${_newvers_sh}"
        return 1
    fi

    local _revision
    local _branch

    while IFS= read -r line; do
        case "$line" in
            REVISION=*)
                _revision="${line#REVISION=\"}"
                _revision="${_revision%\"}"
                ;;
            BRANCH=*)
                _branch="${line#BRANCH=\"}"
                _branch="${_branch%\"}"
                ;;
        esac
    done < <(grep -E '^(REVISION|BRANCH)=' "$_newvers_sh")

    if [[ "${_branch}" == RELEASE* ]]; then
        local version_number="${_revision}${_branch#RELEASE-}"
    else
        local version_number="${_revision}"
    fi

    echo "${version_number}"
}

build-staging() {
    local _target=${BSDKIT_DATA}/release-${_version}-${_arch}

    if [ -d "${OS_RELDIR}/ftp" ]; then
        if [ -d "${_target}" ]; then
            rm -r -f ${_target}
        fi

        mkdir -p ${_target}
        cp ${OS_RELDIR}/ftp/* ${_target}
    fi

    ${BSDKIT_PATH}/bsdkit build-setup-staging \
        ${BSDKIT_DATA}/staging-${_version}-${_arch} \
        . \
        ${BSDKIT_DATA}/release-${_version}-${_arch} \
        ${BSDKIT_DATA}/packages-FreeBSD:${OS_MAJOR}:${_arch}-default-nox11
}

build-iso() {
    local _iso=${BSDKIT_DATA}/iso/release-${_version}-${_arch}.iso
    local _release="none"
    local _packages="none"

    if [ -n "${_with_packages}" ]; then
        _iso=${BSDKIT_DATA}/iso/release-${_version}-${_arch}.full.iso
        _release=${BSDKIT_DATA}/release-${_version}-${_arch}
        _packages=${BSDKIT_DATA}/packages-FreeBSD:${OS_MAJOR}:${_arch}-default-nox11
    fi

    ${BSDKIT_PATH}/bsdkit build-setup-iso \
        ${_iso} \
        ${BSDKIT_DATA}/staging-${_version}-${_arch} \
        ${_release} \
        ${_packages}
}

build-usb() {
    local _iso=${BSDKIT_DATA}/iso/release-${_version}-${_arch}.iso
    local _usb=${BSDKIT_DATA}/iso/release-${_version}-${_arch}.img

    if [ -n "${_with_packages}" ]; then
        _iso=${BSDKIT_DATA}/iso/release-${_version}-${_arch}.full.iso
        _usb=${BSDKIT_DATA}/iso/release-${_version}-${_arch}.full.img
    fi

    ${BSDKIT_PATH}/bsdkit build-setup-img ${_iso} ${_usb}
}

if [ -n "${_build_release}" ]; then
    build-release
fi

if [ -n "${_build_staging}" ]; then
    build-staging
fi

if [ -n "${_build_iso}" ]; then
    build-iso
fi

if [ -n "${_build_usb}" ]; then
    build-usb
fi
