#!/usr/bin/env zsh

setopt errreturn nounset pipefail

SCRIPT_PATH="$(dirname $(realpath $0))"
SCRIPT_NAME="$(basename $0)"

source ${SCRIPT_PATH}/../lib/system.inc.sh
source ${SCRIPT_PATH}/../lib/colors.inc.sh
source ${SCRIPT_PATH}/../lib/hr-to-bytes.inc.sh
source ${SCRIPT_PATH}/../lib/is-yes.inc.sh
source ${SCRIPT_PATH}/../lib/yaml.inc.sh
source ${SCRIPT_PATH}/../lib/zfs.inc.sh

if [ "$(uname -s)" != "FreeBSD" ]; then
    error "Must be executed on FreeBSD."
fi

BSDKIT_PATH="$(realpath ${SCRIPT_PATH}/../)"

if [ -x /usr/local/bin/vim ]; then
    export EDITOR=/usr/local/bin/vim
fi

# ===========================================================================

rewrite-filesystem() {
    local _option

    local _source_filesystem

    OPTIND=1
    while getopts "s:" _option; do
        case "${_option}" in
            s)
                _source_filesystem="${OPTARG}"
                ;;
            *)
                error "unrecognized option."
                ;;
        esac
    done

    [ -n "${_source_filesystem}" ] || error "_source_filesystem required."

    local _target_filesystem
    local _snapshot_name

    _snapshot_name=$(uuidgen | cut -d - -f 1)
    _target_filesystem=${_source_filesystem}.${_snapshot_name}

    zfs destroy -r "${_source_filesystem}"@"${_snapshot_name}" > /dev/null 2>&1 || :
    zfs unmount -f "${_source_filesystem}"
    zfs snapshot -r "${_source_filesystem}"@"${_snapshot_name}"
    zfs send --verbose --replicate --props --large-block --embed "${_source_filesystem}"@"${_snapshot_name}" |
        zfs receive -v -u -F "${_target_filesystem}"
    zfs destroy -r -f "${_source_filesystem}"@"${_snapshot_name}"
    zfs destroy -r -f "${_target_filesystem}"@"${_snapshot_name}"
    zfs destroy -r -f "${_source_filesystem}"
    zfs rename "${_target_filesystem}" "${_source_filesystem}"

    local _filesystem

    for _filesystem in $(zfs list -H -o name -t filesystem -r "${_source_filesystem}"); do
        # BD584E0F-28D6-4409-956D-F9B1468C2DD9
        zfs get -H all "${_filesystem}" |
            filter-properties |
            cut -s -f 2 |
            sort |
            uniq |
            xargs -n1 -J % echo zfs inherit -S % "${_filesystem}" |
            sh -x
    done

    # 8E95F488-BE4B-48F6-9FEE-C58CBBFD25BC
    zfs get -s received -H -r all "${_source_filesystem}" |
        filter-properties |
        awk '
$2 != "mountpoint" {
  print "zfs set " $2 "=" $3 " " $1;
}

$2 == "mountpoint" {
  gsub("/altroot", "", $3);

  if ($3 == "") {
    $3 = "/";
  }

  print "zfs set " $2 "=" $3 " " $1
}
' | sh -x

    for _filesystem in $(zfs list -H -o name -r "${_source_filesystem}"); do
        if [ "$(zfs get -H -o value canmount "${_filesystem}")" = "on" ]; then
            zfs mount "${_filesystem}"
        fi
    done
}

rewrite-filesystem "$@"
