#!/usr/bin/env zsh

setopt errreturn nounset pipefail

SCRIPT_PATH="$(dirname $(realpath $0))"
SCRIPT_NAME="$(basename $0)"

source ${SCRIPT_PATH}/../lib/colors.inc
source ${SCRIPT_PATH}/../lib/hr-to-bytes.inc
source ${SCRIPT_PATH}/../lib/is-yes.inc
source ${SCRIPT_PATH}/../lib/yaml.inc

if [ "$(uname -s)" != "FreeBSD" ]; then
    error "Must be executed on FreeBSD."
    exit 1
fi

BSDKIT_PATH="$(realpath ${SCRIPT_PATH}/../)"

# ===========================================================================

: ${BSDKIT_ROOT_URL:="http://hub.olgeni.com/FreeBSD"}
: ${BSDKIT_VERSION:=""}
: ${BSDKIT_ARCH:="amd64"}
: ${DESTDIR:=""}
: ${BOOTENV_ENABLE:="default"}
: ${BOOTENV_NAME:="$(date +%F.%H%M)"}
: ${BOOTENV_MOUNT:="/mnt"}
: ${FETCH_ONLY:="no"}
: ${UPGRADE_PACKAGES:="no"}
: ${REBUILD_PORTS:="no"}
: ${PV_UPDATE_DELAY:="0.1"}

: ${_install_src:="no"}
: ${_install_debug:="no"}
: ${_install_tests:="no"}
: ${_proc_mounted:="no"}

_mountpoint_list=()

get-file-fs() {
    local _directory="$1"

    df -T ${_directory} | tail -n +2 | awk '{ print $2; }'
}

file-on-fs() {
    local _directory="$1"
    local _type="$2"

    [ "$(get-file-fs ${_directory})" = "${_type}" ]
}

file-on-ufs() {
    local _directory="$1"

    file-on-fs ${_directory} "ufs"
}

file-on-zfs() {
    local _directory="$1"

    file-on-fs ${_directory} "zfs"
}

cleanup() {
    if is-yes ${BOOTENV_ENABLE}; then
        for ((i=${#_mountpoint_list[@]}; i>=1; i--)); do
            if ${BSDKIT_PATH}/bsdkit is-mount-point ${BOOTENV_MOUNT}${_mountpoint_list[i]}; then
                umount -f ${BOOTENV_MOUNT}${_mountpoint_list[i]}
            fi
        done

        if mount | cut -w -f 3 | fgrep -q "${BOOTENV_MOUNT}/dev"; then
            if ${BSDKIT_PATH}/bsdkit is-mount-point ${BOOTENV_MOUNT}/dev; then
                umount -f ${BOOTENV_MOUNT}/dev
            fi
        fi

        if mount | cut -w -f 3 | fgrep -q "${BOOTENV_MOUNT}"; then
            if ${BSDKIT_PATH}/bsdkit is-mount-point ${BOOTENV_MOUNT}; then
                bectl umount -f ${BOOTENV_NAME}
            fi
        fi
    else
        if [ -z "${DESTDIR}" ]; then
            if ! mount | cut -w -f 3 | fgrep -q "/proc"; then
                if is-yes ${_proc_mounted}; then
                    mount /proc
                fi
            fi
        fi
    fi
}

osmajor() {
    local _destdir="$1"

    awk '/^\#define[[:blank:]]__FreeBSD_version/ { print substr($3, 1, 2); }' ${_destdir}/usr/include/sys/param.h
}

rebuild-port() {
    local _port="$1"

    if ! pkg info -q ${_port}; then
        return 0
    fi

    if ! [ $(osmajor /) = $(osmajor ${BOOTENV_MOUNT}) -a -d ${BOOTENV_MOUNT}/usr/ports/${_port} ]; then
        return 0
    fi

    mount -t devfs devfs ${BOOTENV_MOUNT}/dev

    pkg -c ${BOOTENV_MOUNT} unlock -y ${_port}
    chroot ${BOOTENV_MOUNT} make -C /usr/ports/${_port} clean all deinstall install
    chroot ${BOOTENV_MOUNT} make -C /usr/ports/${_port} clean
    pkg -c ${BOOTENV_MOUNT} lock -y ${_port}

    umount -f ${BOOTENV_MOUNT}/dev
}

remove-nouarch-files() {
    local _directory="$1"

    if [ ! -d ${_directory} ]; then
        return 0
    fi

    local _file_list=$(mktemp -t ${SCRIPT_NAME}.XXXXXX)
    local _directory_list=$(mktemp -t ${SCRIPT_NAME}.XXXXXX)

    find -s ${_directory} -flags nouarch -type f >> ${_file_list}
    find -s ${_directory} -flags nouarch -type d | sed -n '1!G;h;$p' >> ${_directory_list}

    cat ${_file_list} | while read _filename; do
        message "Removing ${_filename}"
        rm -f ${_filename}
    done

    cat ${_directory_list} | while read _directory; do
        if [ -z "$(ls -A ${_directory})" ]; then
            message "Removing ${_directory}"
            rmdir ${_directory}
        fi
    done

    rm -f ${_file_list}
    rm -f ${_directory_list}
}

update-boot-loader() {
    _disks="$(sysctl -n kern.disks | rs 0 1 | sort | rs 1 0)"

    for _disk in ${(s/ /)_disks}; do
        case "${_disk}" in
            cd[0-9]*)
                continue
                ;;
        esac

        if echo "$(gpart show "${_disk}" 2>/dev/null)" | grep -qF '[CORRUPT]'; then
            error "GPT on disk ${_disk} is marked as CORRUPT"
        fi
    done

    _efi_mount_point="${DESTDIR}/boot/efi"

    mkdir -p "${_efi_mount_point}"

    for _disk in ${(s/ /)_disks}; do
        case "${_disk}" in
            cd[0-9]*)
                continue
                ;;
        esac

        _efi_partitions=$(gpart show -p "${_disk}" 2>/dev/null | grep -w efi | awk '{ print $3 }' || :)
        _freebsd_boot_partitions=$(gpart show -p "${_disk}" 2>/dev/null | grep -w freebsd-boot | awk '{ print $3 }' || :)
        _freebsd_zfs_partitions=$(gpart show -p "${_disk}" 2>/dev/null | grep -w freebsd-zfs | awk '{ print $3 }' || :)

        if [ -n "${_freebsd_boot_partitions}" ]; then
            for _partition in ${(s/ /)_freebsd_boot_partitions}; do
                message "Checking freebsd-boot partition ${_partition}"

                local _index=$(echo ${_partition} | sed -E 's/.*p([0-9]+)$/\1/')

                if [ -z "${_index}" ]; then
                    error "Failed to determine partition index (${_partition})"
                fi

                if [ -n "${_freebsd_zfs_partitions}" ]; then
                    message "Upgrading boot loader on ${_partition} (gptzfsboot)"
                    gpart bootcode -b "${DESTDIR}/boot/pmbr" -p "${DESTDIR}/boot/gptzfsboot" -i ${_index} "${_disk}"
                else
                    message "Upgrading boot loader on ${_partition} (gptboot)"
                    gpart bootcode -b "${DESTDIR}/boot/pmbr" -p "${DESTDIR}/boot/gptboot" -i ${_index} "${_disk}"
                fi
            done
        fi

        if [ -n "${_efi_partitions}" ]; then
            for _partition in ${(s/ /)_efi_partitions}; do
                message "Checking EFI partition ${_partition}"

                umount -f "/dev/${_partition}" >/dev/null 2>&1 || :

                if ! mount -t msdosfs "/dev/${_partition}" "${_efi_mount_point}" >/dev/null 2>&1; then
                    warning "Failed to mount EFI partition ${_partition}"
                    continue
                fi

                if [ -d "${_efi_mount_point}/efi/boot" ]; then
                    message "Upgrading EFI boot loader on ${_partition}"
                    install -v "${DESTDIR}/boot/loader.efi" "${_efi_mount_point}/efi/boot/bootx64.efi.new"
                    mv -v "${_efi_mount_point}/efi/boot/bootx64.efi.new" "${_efi_mount_point}/efi/boot/bootx64.efi"

                    if [ ! -f "${_efi_mount_point}/efi/boot/startup.nsh" ]; then
                        echo "BOOTx64.efi" > "${_efi_mount_point}/efi/boot/startup.nsh"
                    fi
                else
                    warning "EFI directory not found for ${_partition}"
                fi

                if ! umount "${_efi_mount_point}" >/dev/null 2>&1; then
                    error "Failed to unmount EFI partition ${_partition}"
                fi
            done
        fi
    done
}

trap cleanup EXIT

if which -s pv > /dev/null 2>&1; then
    CAT_CMD="pv -i ${PV_UPDATE_DELAY} -c -w 75"
else
    CAT_CMD="/bin/cat"
fi

if mount | cut -w -f 3 | fgrep -q "/proc"; then
    _proc_mounted="yes"
fi

OPTIND=1
while getopts "a:b:d:eEFn:p:r:v:" OPT; do
    case ${OPT} in
        a)
            BSDKIT_ARCH=${OPTARG}
            ;;
        b)
            REBUILD_PORTS="yes"
            ;;
        d)
            DESTDIR=${OPTARG%/}
            ;;
        e)
            BOOTENV_ENABLE="yes"
            ;;
        E)
            BOOTENV_ENABLE="no"
            ;;
        F)
            FETCH_ONLY="yes"
            ;;
        n)
            BOOTENV_NAME=${OPTARG}
            ;;
        p)
            UPGRADE_PACKAGES="yes"
            ;;
        r)
            BSDKIT_ROOT_URL=${OPTARG}
            ;;
        v)
            BSDKIT_VERSION=${OPTARG}
            ;;
        *)
            exit 64 # EX_USAGE
            ;;
    esac
done

shift $((OPTIND - 1))

if [ -d ${DESTDIR}/.base ]; then
    error "Destination directory is thin jail"
fi

if [ -z "${BSDKIT_VERSION}" ]; then
    BSDKIT_VERSION="$(${BSDKIT_PATH}/bsdkit get-os-version)"
    message "Using current version: ${BSDKIT_VERSION}"
fi

_security_jail_jailed="no"

if sysctl -n security.jail.jailed > /dev/null 2>&1; then
    if [ "$(sysctl -n security.jail.jailed)" = "1" ]; then
        _security_jail_jailed="yes"
        BOOTENV_ENABLE="no"
    fi
fi

if kenv -q zfs_be_root > /dev/null 2>&1; then
    if [ "${BOOTENV_ENABLE}" = "default" ]; then
        if [ -z "${DESTDIR}" ]; then
            BOOTENV_ENABLE="yes"
        else
            BOOTENV_ENABLE="no"
        fi
    fi
else
    BOOTENV_ENABLE="no"
fi

if ! is-yes ${FETCH_ONLY}; then
    if [ "${DESTDIR}" != "" ] && is-yes ${BOOTENV_ENABLE}; then
        error "incompatible BOOTENV_ENABLE and DESTDIR"
    fi

    if is-yes ${BOOTENV_ENABLE}; then
        which bectl > /dev/null 2>&1 || error "missing requirement: bectl"
    fi
fi

if [ -f ${DESTDIR}/usr/src/Makefile ]; then
    _install_src="yes"
fi

if [ -f ${DESTDIR}/usr/lib/debug/bin/sh.debug ]; then
    _install_debug="yes"
fi

if [ -f ${DESTDIR}/usr/tests/Kyuafile ]; then
    _install_tests="yes"
fi

_release=${BSDKIT_ROOT_URL}/release-${BSDKIT_VERSION}-${BSDKIT_ARCH}

_distdir=/usr/freebsd-dist/${BSDKIT_VERSION}-${BSDKIT_ARCH}

mkdir -p ${_distdir}

cd ${_distdir}

message "Fetching MANIFEST file"
fetch -q ${_release}/MANIFEST || error "Failed to fetch MANIFEST file"

message "Fetching RELEASE file"
fetch -q ${_release}/RELEASE || error "Failed to fetch RELEASE file"

message "Fetching etcupdate.tar.bz2 file"
fetch -q ${_release}/etcupdate.tar.bz2 || error "Failed to fetch etcupdate.tar.bz2 file"

# base-dbg.txz    [sha256]  [size]  base_dbg    "Base system (Debugging)"                     off
# base.txz        [sha256]  [size]  base        "Base system (MANDATORY)"                     on
# doc.txz         [sha256]  [size]  doc         "Additional Documentation"                    off
# kernel-dbg.txz  [sha256]  [size]  kernel_dbg  "Kernel (Debugging)"                          off
# kernel.txz      [sha256]  [size]  kernel      "Kernel (MANDATORY)"                          on
# lib32-dbg.txz   [sha256]  [size]  lib32_dbg   "32-bit compatibility libraries (Debugging)"  off
# lib32.txz       [sha256]  [size]  lib32       "32-bit compatibility libraries"              on
# ports.txz       [sha256]  [size]  ports       "Ports tree"                                  on
# src.txz         [sha256]  [size]  src         "System source tree"                          off
# tests.txz       [sha256]  [size]  tests       "Test suite"                                  off

cat MANIFEST | while read _filename _sha256 _size _package _desc _enable; do
    if ! is-yes ${_install_src} && [ ${_package} = "src" ]; then
        continue
    fi

    if ! is-yes ${_install_debug} && [ ${_package} != "${_package%_dbg}" ]; then
        continue
    fi

    if ! is-yes ${_install_tests} && [ ${_package} = "tests" ]; then
        continue
    fi

    if [ ${_package} = "ports" ]; then
        continue
    fi

    if [ -f "${_filename}" ]; then
        message "Checking ${_filename}"
        _sha256_local=$(${=CAT_CMD} "${_filename}" | sha256 -q)
    else
        _sha256_local="0"
    fi

    while [ "${_sha256}" != "${_sha256_local}" ]; do
        fetch ${_release}/${_filename}
        _sha256_local=$(sha256 -q "${_filename}")
    done
done

if is-yes ${FETCH_ONLY}; then
    message "Release downloaded successfully"
    exit 0
fi

_destdir_fs=$(zfs list -H -o mounted,mountpoint,name | awk "\$1 == \"yes\" && \$2 == \"${DESTDIR}\" { print \$3; }")

if [ -n "${_destdir_fs}" ]; then
    zfs snapshot "${_destdir_fs}@$(date +%F.%H%M)"
fi

if is-yes ${BOOTENV_ENABLE}; then
    if mount | cut -w -f 3 | fgrep -q "${BOOTENV_MOUNT}"; then
        error "mount point '${BOOTENV_MOUNT}' already in use"
    fi

    bectl create ${BOOTENV_NAME}
    bectl mount ${BOOTENV_NAME} ${BOOTENV_MOUNT}

    if mount | cut -w -f 3 | fgrep -q "/usr/src"; then
        _mountpoint_list+=("/usr/src")
    fi

    if mount | cut -w -f 3 | fgrep -q "/usr/ports"; then
        _mountpoint_list+=("/usr/ports")
    fi

    mount -p | awk '$2 ~ "^/var(/|$)" { print $2 }' | while read _mountpoint; do
        _mountpoint_list+=(${_mountpoint})
    done

    for ((i=1; i<=${#_mountpoint_list[@]}; i++)); do
        mount -t nullfs ${_mountpoint_list[i]} ${BOOTENV_MOUNT}${_mountpoint_list[i]}
    done

    mount -t devfs devfs ${BOOTENV_MOUNT}/dev

    DESTDIR=${BOOTENV_MOUNT}
else
    if [ -z "${DESTDIR}" ]; then
        if is-yes ${_proc_mounted}; then
            umount -f /proc
        fi
    fi
fi

_srcdir=/usr/src

if [ -f ${DESTDIR}/usr/src/Makefile ]; then
    _srcdir=${DESTDIR}/usr/src
fi

if [ -t 0 ]; then
    etcupdate resolve -D ${DESTDIR}/
fi

export PATH=/rescue:${PATH}

if [ ! -d ${DESTDIR}/etc/rc.d ]; then
    error "missing ${DESTDIR}/etc/rc.d"
fi

find \
    ${DESTDIR}/bin \
    ${DESTDIR}/lib \
    ${DESTDIR}/libexec \
    ${DESTDIR}/sbin \
    ${DESTDIR}/usr/bin \
    ${DESTDIR}/usr/lib \
    ${DESTDIR}/usr/lib32 \
    -flags -schg \
    -exec chflags noschg {} \;

if [ -f ${_distdir}/etcupdate.tar.bz2 ]; then
    etcupdate -F -p -D ${DESTDIR}/ -t ${_distdir}/etcupdate.tar.bz2
elif [ -f ${_srcdir}/Makefile ]; then
    etcupdate -F -p -D ${DESTDIR}/ -s ${_srcdir}
fi

if [ -t 0 ]; then
    etcupdate resolve -p -D ${DESTDIR}/
fi

_readonly_directory_list=(
    "bin"
    "boot"
    "lib"
    "libexec"
    "rescue"
    "sbin"
    "usr/bin"
    "usr/include"
    "usr/lib"
    "usr/lib32"
    "usr/libdata"
    "usr/libexec"
    "usr/sbin"
    "usr/share"
    "usr/src"
    "usr/tests"
)

if file-on-zfs ${DESTDIR:-/}; then
    for _directory in ${_readonly_directory_list}; do
        if [ -d ${DESTDIR}/${_directory} ]; then
            chflags -R uarch ${DESTDIR}/${_directory}
        fi
    done

    for _directory in /boot/loader.conf /boot/loader.conf.local /boot/loader.conf.d; do
        if [ -e ${DESTDIR}${_directory} ]; then
            chflags -R uarch ${DESTDIR}${_directory}
        fi
    done

    if [ -n "$(ls -A ${DESTDIR}/boot/modules)" ]; then
        chflags -R uarch ${DESTDIR}/boot/modules/*
    fi
fi

cat MANIFEST | while read _filename _sha256 _size _package _desc _enable; do
    _extract="no"
    _options=()

    if ! is-yes ${_install_debug} && [ ${_package} != ${_package%_dbg} ]; then
        continue
    fi

    if ! is-yes ${_install_tests} && [ ${_package} = "tests" ]; then
        continue
    fi

    if ! is-yes ${_install_src} && [ ${_package} = "src" ]; then
        continue
    fi

    case ${_package} in
        kernel*)
            if [ -f "${DESTDIR}/boot/kernel/kernel" ]; then
                _extract="yes"
            fi
            _options+="--exclude ./usr"
            ;;

        base)
            _options+="--exclude ./.cshrc"
            _options+="--exclude ./.profile"
            _options+="--exclude ./etc"
            _options+="--exclude ./root"
            _options+="--exclude ./tmp"
            _options+="--exclude ./var"

            if ! is-yes ${_install_tests}; then
                _options+="--exclude ./usr/tests"
            fi

            _extract="yes"
            ;;

        ports) ;;

        src)
            if file-on-zfs ${DESTDIR:-/}; then
                for _arch in i386 amd64; do
                    if [ -f ${DESTDIR}/usr/src/sys/${_arch}/conf/BSDKIT ]; then
                        chflags uarch ${DESTDIR}/usr/src/sys/${_arch}/conf/BSDKIT
                    fi
                done
            fi

            _options+="--no-same-owner"
            _extract="yes"
            ;;

        *)
            _extract="yes"
            ;;
    esac

    if is-yes ${_extract}; then
        message "Extracting ${_filename}"

        # In the Zsh shell, `${=VAR_NAME}` is a parameter expansion that
        # performs word splitting on the value of `VAR_NAME`.

        local _stderr_log=$(mktemp -t ${SCRIPT_NAME}.XXXXXX)

        local _attempt_limit=2
        local _attempt_count=0

        while [ ${_attempt_count} -lt ${_attempt_limit} ]; do
            if ${=CAT_CMD} ${_distdir}/${_filename} | tar -x -p -U -C ${DESTDIR}/ -f - ${=_options[*]} 2> ${_stderr_log}; then
                break
            else
                warning "Failed to extract ${_filename}, retrying"
                cat ${_stderr_log}

                # Sample error: "/usr/src/sys/contrib/openzfs/cmd/zvol_wait: Could not unlink"
                local _target

                grep "Could not unlink" ${_stderr_log} | awk -F ": " '{print $1}' | while read -r _target; do
                    warning "Removing ${_target} due to 'Could not unlink' error"
                    rm -r -f ${DESTDIR}/${_target}
                done

                _attempt_count=$(( _attempt_count + 1 ))
                continue
            fi
        done

        if [ ${_attempt_count} -eq ${_attempt_limit} ]; then
            error "Failed to extract ${_filename} after ${_attempt_limit} attempts"
        fi

        rm -f ${_stderr_log}
    fi
done

if [ -f ${_distdir}/etcupdate.tar.bz2 ]; then
    message "Running etcupdate (tar)"
    etcupdate -F -I '*.cf' -D ${DESTDIR}/ -t ${_distdir}/etcupdate.tar.bz2
elif [ -f ${_srcdir}/Makefile ]; then
    message "Running etcupdate (src)"
    etcupdate -F -I '*.cf' -D ${DESTDIR}/ -s ${_srcdir}
fi

if file-on-zfs ${DESTDIR:-/}; then
    message "Removing obsolete files"

    for _directory in ${_readonly_directory_list}; do
        if [ -d ${DESTDIR}/${_directory} ]; then
            remove-nouarch-files ${DESTDIR}/${_directory}
        fi
    done
fi

message "Running mtree"

if [ -f ${DESTDIR}/etc/mtree/BSD.root.dist ]; then
    mtree -ideU -N ${DESTDIR}/etc -f ${DESTDIR}/etc/mtree/BSD.root.dist -p ${DESTDIR}/
fi

if [ -f ${DESTDIR}/etc/mtree/BSD.usr.dist ]; then
    mtree -ideU -N ${DESTDIR}/etc -f ${DESTDIR}/etc/mtree/BSD.usr.dist -p ${DESTDIR}/usr
fi

if [ -f ${DESTDIR}/etc/mtree/BSD.var.dist ]; then
    mtree -ideU -N ${DESTDIR}/etc -f ${DESTDIR}/etc/mtree/BSD.var.dist -p ${DESTDIR}/var
fi

if [ -f ${DESTDIR}/etc/mtree/BSD.sendmail.dist ]; then
    mtree -ideU -N ${DESTDIR}/etc -f ${DESTDIR}/etc/mtree/BSD.sendmail.dist -p ${DESTDIR}/
fi

if [ -f ${DESTDIR}/etc/mtree/BSD.lib32.dist ]; then
    if [ -d ${DESTDIR}/usr/lib32 ]; then
        mtree -ideU -N ${DESTDIR}/etc -f ${DESTDIR}/etc/mtree/BSD.lib32.dist -p ${DESTDIR}/usr
    fi
fi

if [ -f ${DESTDIR}/etc/mtree/BSD.include.dist ]; then
    if [ -d ${DESTDIR}/usr/include ]; then
        mtree -ideU -N ${DESTDIR}/etc -f ${DESTDIR}/etc/mtree/BSD.include.dist -p ${DESTDIR}/usr/include
    fi
fi

if [ -f ${DESTDIR}/etc/mtree/BSD.tests.dist ]; then
    if [ -d ${DESTDIR}/usr/tests ]; then
        mtree -ideU -N ${DESTDIR}/etc -f ${DESTDIR}/etc/mtree/BSD.tests.dist -p ${DESTDIR}/usr/tests
    fi
fi

if [ -f ${DESTDIR}/etc/mtree/BSD.debug.dist ]; then
    if [ -d ${DESTDIR}/usr/lib/debug ]; then
        mtree -ideU -N ${DESTDIR}/etc -f ${DESTDIR}/etc/mtree/BSD.debug.dist -p ${DESTDIR}/usr/lib
    fi
fi

message "Running newaliases"
chroot ${DESTDIR}/ newaliases

if [ -f ${_srcdir}/Makefile ]; then
    cd ${_srcdir}

    message "Running delete-old"

    {
        set +o pipefail
        yes y | make delete-old DESTDIR=${DESTDIR}/ > /dev/null 2>&1
        set -o pipefail
    }

    # message "Running delete-old-libs"
    # yes y | make delete-old-libs DESTDIR=${DESTDIR}/ > /dev/null 2>&1
fi

# Remove obsolete mixer state files when upgrading to FreeBSD 14.
for _file in ${DESTDIR}/var/db/mixer*-state(N); do
    # Content is like "vol 75:75 pcm 75:75..."
    if awk 'NR == 1 && $1 == "vol" { exit 0; }' ${_file} > /dev/null 2>&1; then
        warning "Removing obsolete mixer state file: ${_file}"
        rm -f ${_file}
    fi
done

if is-yes ${BOOTENV_ENABLE}; then
    if is-yes ${UPGRADE_PACKAGES}; then
        if pkg -c ${BOOTENV_MOUNT} update --repository bsdkit --force; then
            pkg -c ${BOOTENV_MOUNT} upgrade --repository bsdkit --yes pkg
            pkg -c ${BOOTENV_MOUNT} upgrade --repository bsdkit --fetch-only --yes
            env HANDLE_RC_SCRIPTS=NO pkg -c ${BOOTENV_MOUNT} upgrade --repository bsdkit --yes
        fi
    fi

    if is-yes ${REBUILD_PORTS}; then
        for _port in $(pkg which -qo /boot/modules/* | sort | uniq); do
            rebuild-port ${_port}
        done
    fi
fi

if [ -z "${DESTDIR}" ]; then
    update-boot-loader
elif [ "${DESTDIR}" = "${BOOTENV_MOUNT}" ] && is-yes ${BOOTENV_ENABLE}; then
    update-boot-loader
fi

if is-yes ${BOOTENV_ENABLE}; then
    for ((i=${#_mountpoint_list[@]}; i>=1; i--)); do
        if ${BSDKIT_PATH}/bsdkit is-mount-point ${BOOTENV_MOUNT}${_mountpoint_list[i]}; then
            umount -f ${BOOTENV_MOUNT}${_mountpoint_list[i]}
        fi
    done

    bectl umount -f ${BOOTENV_NAME}
    bectl activate ${BOOTENV_NAME}
    bectl list
fi

message "Upgrade complete."
