#!/bin/sh

# shellcheck disable=SC3043

set -e -u -o pipefail

SCRIPT_PATH="$(dirname $(realpath $0))"
SCRIPT_NAME="$(basename $0)"

message() {
    echo "[${SCRIPT_NAME}] $*"
}

error() {
    echo "[${SCRIPT_NAME}] $*" >&2
    exit 1
}

filter_properties() {
    awk '
BEGIN {
  read_only["available"] = 1;
  read_only["casesensitivity"] = 1;
  read_only["compressratio"] = 1;
  read_only["createtxg"] = 1;
  read_only["creation"] = 1;
  read_only["encryption"] = 1;
  read_only["filesystem_count"] = 1;
  read_only["guid"] = 1;
  read_only["keyformat"] = 1;
  read_only["keylocation"] = 1;
  read_only["logicalreferenced"] = 1;
  read_only["logicalused"] = 1;
  read_only["mlslabel"] = 1;
  read_only["mounted"] = 1;
  read_only["normalization"] = 1;
  read_only["objsetid"] = 1;
  read_only["origin"] = 1;
  read_only["pbkdf2iters"] = 1;
  read_only["refcompressratio"] = 1;
  read_only["referenced"] = 1;
  read_only["snapshot_count"] = 1;
  read_only["type"] = 1;
  read_only["used"] = 1;
  read_only["usedbychildren"] = 1;
  read_only["usedbydataset"] = 1;
  read_only["usedbyrefreservation"] = 1;
  read_only["usedbysnapshots"] = 1;
  read_only["utf8only"] = 1;
  read_only["version"] = 1;
  read_only["written"] = 1;
}

{
  if (!read_only[$2]) {
    print;
  }
}
'
}

rewrite_pool() {
    local _option

    local _source_pool
    local _target_pool
    local _source_device
    local _target_device

    _target_pool=""

    OPTIND=1
    while getopts "p:n:s:t:" _option; do
        case "${_option}" in
            p)
                _source_pool="${OPTARG}"
                ;;
            n)
                _target_pool="${OPTARG}"
                ;;
            s)
                _source_device="${OPTARG}"
                ;;
            t)
                _target_device="${OPTARG}"
                ;;
            *)
                error "unrecognized option."
                ;;
        esac
    done

    if [ -z "${_target_pool}" ]; then
        _target_pool="${_source_pool}"
    fi

    [ -n "${_source_pool}" ] || error "_source_pool required."
    [ -n "${_source_device}" ] || error "_source_device required."
    [ -n "${_target_device}" ] || error "_target_device required."

    local _snapshot_name
    local _target_pool_alias

    _snapshot_name=$(uuidgen | cut -d - -f 1)
    _target_pool_alias="${_target_pool}"-"${_snapshot_name}"

    zpool detach "${_source_pool}" "${_target_device}"
    mkdir -p /altroot
    zpool create -R /altroot -t "${_target_pool_alias}" "${_target_pool}" "${_target_device}"
    zfs destroy -r "${_source_pool}"@"${_snapshot_name}" > /dev/null 2>&1 || :
    zfs snapshot -r "${_source_pool}"@"${_snapshot_name}"
    zfs send --verbose --replicate --props --large-block --embed "${_source_pool}"@"${_snapshot_name}" |
        zfs receive -v -u -F -d "${_target_pool_alias}"
    zfs destroy -r -f "${_source_pool}"@"${_snapshot_name}"
    zfs destroy -r -f "${_target_pool_alias}"@"${_snapshot_name}"

    local _filesystem

    for _filesystem in $(zfs list -H -o name -t filesystem -r "${_target_pool_alias}"); do
        # BD584E0F-28D6-4409-956D-F9B1468C2DD9
        zfs get -H all "${_filesystem}" |
            filter_properties |
            cut -s -f 2 |
            sort |
            uniq |
            xargs -n1 -J % echo zfs inherit -S % "${_filesystem}" |
            sh -x
    done

    # 8E95F488-BE4B-48F6-9FEE-C58CBBFD25BC
    zfs get -s received -H -r all "${_target_pool_alias}" |
        filter_properties |
        awk '
$2 != "mountpoint" {
  print "zfs set " $2 "=" $3 " " $1;
}

$2 == "mountpoint" {
  gsub("/altroot", "", $3);

  if ($3 == "") {
    $3 = "/";
  }

  print "zfs set " $2 "=" $3 " " $1
}
' | sh -x

    local _source_bootfs
    local _target_bootfs

    if [ "$(zpool get -H -o source bootfs "${_source_pool}")" = "local" ]; then
        _source_bootfs=$(zpool get -H -o value bootfs "${_source_pool}")
        _target_bootfs=$(echo "${_source_bootfs}" | sed -e "s/${_source_pool}/${_target_pool_alias}/")

        zpool set bootfs="${_target_bootfs}" "${_target_pool_alias}"
        zpool set bootfs="" "${_source_pool}"
    fi

    zpool destroy -f "${_source_pool}"

    zpool labelclear -f "${_source_device}"

    zpool attach "${_target_pool_alias}" "${_target_device}" "${_source_device}"
}

rewrite_pool "$@"
