---
- name: Remove /usr/lib/debug directory
  file:
    path: /usr/lib/debug
    state: absent

- name: Remove /usr/tests directory
  file:
    path: /usr/tests
    state: absent

- name: Remove /usr/local/etc/portmaster.rc
  file:
    path: /usr/local/etc/portmaster.rc
    state: absent

- name: Remove /var/log/console
  file:
    path: /var/log/console
    state: absent

- name: Remove fscd_enable from /etc/rc.conf
  lineinfile:
    path: /etc/rc.conf
    regexp: '^fscd_enable'
    state: absent

- name: Remove sysutils/fsc package
  community.general.pkgng:
    name: sysutils/fsc
    state: absent

- name: Remove misc/buffer package
  community.general.pkgng:
    name: misc/buffer
    state: absent

- name: Check if FreeBSD version is 14 or above
  set_fact:
    is_freebsd_14_or_above: "{{ ansible_distribution_version is version('14.0', '>=') }}"

- name: Check if /var/db/portsnap contains any files
  find:
    paths: /var/db/portsnap
    file_type: any
  register: find_var_db_portsnap

- name: Clean contents of /var/db/portsnap if FreeBSD version is 14 or above
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ find_var_db_portsnap.files }}"
  when: is_freebsd_14_or_above
