---
- name: Remove /usr/lib/debug directory
  file:
    path: /usr/lib/debug
    state: absent

- name: Remove /usr/tests directory
  file:
    path: /usr/tests
    state: absent

- name: Remove /usr/local/etc/portmaster.rc
  file:
    path: /usr/local/etc/portmaster.rc
    state: absent

- name: Remove /var/log/console
  file:
    path: /var/log/console
    state: absent
