---
- name: bsdkit_pkgdir
  when: is_host_install and zfs_available
  block:
    - name: Check /var/db/pkg
      stat:
        path: /var/db/pkg
      register: stat_var_db_pkg

    - name: Migrate /var/db/pkg to /usr/local/pkg
      when: (stat_var_db_pkg.stat.isdir is defined) and (stat_var_db_pkg.stat.isdir) and (not stat_var_db_pkg.stat.islnk)
      shell: |
        set -e -u -o pipefail
        mkdir /usr/local/pkg/
        mv /var/db/pkg/* /usr/local/pkg/
        rmdir /var/db/pkg
        ln -s -f /usr/local/pkg /var/db/pkg
