#!/bin/sh

# PROVIDE: bsdkit_provision
# REQUIRE: DAEMON
# KEYWORD: firstboot

. /etc/rc.subr

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin

name="bsdkit_provision"
desc="Run bsdkit provision"
start_cmd="bsdkit_provision_start"
stop_cmd=":"
rcvar="bsdkit_provision_enable"

bsdkit_provision_start()
{
    _index=$(gpart show | awk '$4 == "freebsd-zfs" { print $3 }')
    _pool=$(/usr/local/bsdkit/bsdkit get_boot_pool)

    gpart recover vtbd0

    gpart resize -i ${_index} vtbd0
    zpool online -e ${_pool} vtbd0p${_index}
    zpool initialize ${_pool}

    sysrc -x bsdkit_provision_enable
    cd /usr/local/bsdkit
    ./bsdkit bsdkit_provision
    service netif restart
    service routing restart
    touch /firstboot-reboot
    rm -f /etc/rc.d/bsdkit_provision
}

load_rc_config $name
run_rc_command "$1"
