#!/bin/sh

# PROVIDE: bsdkit_provision
# REQUIRE: DAEMON
# KEYWORD: firstboot

. /etc/rc.subr

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin

name="bsdkit_provision"
desc="Run bsdkit provision"
start_cmd="bsdkit_provision_start"
stop_cmd=":"
rcvar="bsdkit_provision_enable"

bsdkit_provision_start() {
    /usr/local/bsdkit/bsdkit provision

    touch /firstboot-reboot

    for _file in /var/log/*; do
        : >${_file}
    done

    newsyslog -C -v
    : >/root/.history

    sysrc -x bsdkit_provision_enable
    rm -f /etc/rc.d/bsdkit_provision
}

load_rc_config $name
run_rc_command "$1"
