#!/bin/sh

# PROVIDE: digitalocean
# REQUIRE: DAEMON
# KEYWORD: firstboot

. /etc/rc.subr

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin

name="digitalocean"
desc="Run bsdkit digitalocean"
start_cmd="digitalocean_start"
stop_cmd=":"
rcvar="digitalocean_enable"

digitalocean_start()
{
    _index=$(gpart show | awk '$4 == "freebsd-zfs" { print $3 }')
    _pool=$(/usr/local/bsdkit/bsdkit get_boot_pool)

    gpart recover vtbd0

    gpart resize -i ${_index} vtbd0
    zpool online -e ${_pool} vtbd0p${_index}
    zpool initialize ${_pool}

    sysrc -x digitalocean_enable
    cd /usr/local/bsdkit
    ./bsdkit digitalocean
    service netif restart
    service routing restart
    touch /firstboot-reboot
    rm -f /etc/rc.d/digitalocean
}

load_rc_config $name
run_rc_command "$1"
