---
- name: "gitlab_runner: install packages"
  pkgng:
    name: "{{ item }}"
    state: present
  loop:
    - devel/gitlab-runner

- name: "gitlab_runner: configure user"
  user:
    name: gitlab-runner
    state: present
    shell: /bin/sh
    create_home: yes
    password: '{{ lookup("password", "/dev/null length=16") | password_hash("sha256") }}'
    update_password: on_create
    home: "{{ gitlab_runner_home }}"

- name: "gitlab_runner: configure rc.conf.d"
  copy:
    content: |
      gitlab_runner_enable="YES"
      gitlab_runner_dir="{{ gitlab_runner_home }}"
    mode: "0644"
    dest: /etc/rc.conf.d/gitlab_runner
  notify:
    - restart_gitlab_runner

- name: "gitlab_runner: verify"
  shell:
    cmd: |
      sudo --user=gitlab-runner zsh <<- "EOF"
      gitlab-runner verify --delete
      EOF
    warn: no
  changed_when: no

- name: "gitlab-runner: list"
  shell:
    cmd: |
      sudo --user=gitlab-runner zsh <<- "EOF"
      gitlab-runner list --config ~gitlab-runner/.gitlab-runner/config.toml 2>&1
      EOF
    warn: no
  changed_when: no
  register: gitlab_runner_list

  # https://docs.gitlab.com/runner/register/
- name: "gitlab_runner: register"
  shell:
    cmd: |
      sudo --user=gitlab-runner zsh <<- "EOF"
      gitlab-runner register \
          --non-interactive \
          --executor shell \
          --tag-list "{{ gitlab_runner_tag_list }}" \
          --config ~gitlab-runner/.gitlab-runner/config.toml \
          --name "{{ gitlab_runner_name }} ({{ ansible_hostname }})" \
          --url {{ gitlab_url }} \
          --registration-token "{{ gitlab_runner_token }}"
      EOF
    warn: no
  when: >
    (gitlab_runner_name is defined)
    and (gitlab_runner_token is defined)
    and (gitlab_runner_tag_list is defined)
    and gitlab_runner_list.stdout.find(gitlab_runner_name + " (" + ansible_hostname + ")") == -1
  notify:
    - restart_gitlab_runner
