---
- name: Remove unnecessary packages (cloud)
  when: is_host_install and platform_is_cloud
  community.general.pkgng:
    name:
      - sysutils/smartmontools
    state: absent

- name: Remove base packages (common)
  community.general.pkgng:
    name:
      - textproc/yq
    state: absent

# b7ee386b-491d-11f1-b886-4c526214c986
- name: Define list of base packages (common)
  set_fact:
    bsdkit_common_base_packages:
      # required
      - devel/git
      - net/py-netaddr
      - ports-mgmt/pkg
      - security/ca_root_nss
      - shells/zsh
      - sysutils/pv
      - textproc/fzf
      - textproc/go-yq
      - textproc/jq
      - textproc/py-pyaml

      # optional
      - archivers/zip
      - comms/kermit
      - devel/bsddialog
      - devel/gum
      - devel/uclcmd
      - editors/bvi
      - editors/nano
      - editors/vim
      - filesystems/exfat
      - filesystems/ext2
      - filesystems/ntfs
      - ftp/curl
      - ftp/lftp
      - lang/python
      - misc/delay
      - misc/gnu-watch
      - misc/inplace
      - misc/mbuffer
      - misc/mc
      - misc/retry
      - net/croc
      - net/rclone
      - net/rsync
      - net/socat
      - net/zerotier
      - security/gnupg
      - security/openvpn
      - security/portacl-rc
      - shells/bash
      - sysutils/ansible
      - sysutils/clone
      - sysutils/cpdup
      - sysutils/ddrescue
      - sysutils/direnv
      - sysutils/facl
      - sysutils/filemon
      - sysutils/flashrom
      - sysutils/hextools
      - sysutils/hfsutils
      - sysutils/htop
      - sysutils/ipmitool
      - sysutils/memtester
      - sysutils/monit
      - sysutils/ncdu
      - sysutils/podman-suite
      - sysutils/renameutils
      - sysutils/rocinante
      - sysutils/runit
      - sysutils/smenu
      - sysutils/spiped
      - sysutils/tmux
      - sysutils/ts
      - sysutils/zfs-allow
      - sysutils/zfs-set
      - sysutils/zpool-set
      - textproc/align
      - textproc/jo
      - textproc/the_silver_searcher
      - www/go-www
      - www/tinyproxy

# b7ee386b-491d-11f1-b886-4c526214c986
- name: Define list of base packages (host)
  set_fact:
    bsdkit_host_packages:
      - sysutils/beadm
      - sysutils/checkrestart
      - sysutils/lsblk

# b7ee386b-491d-11f1-b886-4c526214c986
- name: Define list of base packages (bare metal)
  set_fact:
    bsdkit_bare_metal_packages:
      - sysutils/smartmontools

- name: Install base packages (common)
  community.general.pkgng:
    name: "{{ bsdkit_common_base_packages }}"
    state: present

- name: Install base packages (host)
  when: is_host_install
  community.general.pkgng:
    name: "{{ bsdkit_host_packages }}"
    state: present

- name: Install base packages (bare metal)
  when: is_host_install and not platform_is_cloud
  community.general.pkgng:
    name: "{{ bsdkit_bare_metal_packages }}"
    state: present

- name: Mark packages as non-removable (common)
  command: "pkg set -A 0 {{ item }}"
  loop: "{{ bsdkit_common_base_packages }}"
  changed_when: false

- name: Mark packages as non-removable (host)
  when: is_host_install
  command: "pkg set -A 0 {{ item }}"
  loop: "{{ bsdkit_host_packages }}"
  changed_when: false

- name: Mark packages as non-removable (bare metal)
  when: is_host_install and not platform_is_cloud
  command: "pkg set -A 0 {{ item }}"
  loop: "{{ bsdkit_bare_metal_packages }}"
  changed_when: false

- name: Configure podman to use ZFS storage driver (when ZFS is available)
  when: zfs_available
  community.general.ini_file:
    path: /usr/local/etc/containers/storage.conf
    section: storage
    option: driver
    value: '"zfs"'
    backup: true
    owner: root
    group: wheel
    mode: "0644"

- name: Configure podman to use VFS storage driver (when ZFS is not available)
  when: not zfs_available
  community.general.ini_file:
    path: /usr/local/etc/containers/storage.conf
    section: storage
    option: driver
    value: '"vfs"'
    backup: true
    owner: root
    group: wheel
    mode: "0644"
