---
- name: Install base packages (host)
  when: is_host_install
  community.general.pkgng:
    name:
      - sysutils/beadm
      - sysutils/checkrestart
      - sysutils/lsblk
    state: present

- name: Install base packages (bare metal)
  when: is_host_install and not platform_is_cloud
  community.general.pkgng:
    name:
      - sysutils/smartmontools
    state: present

- name: Remove unnecessary packages (cloud)
  when: is_host_install and platform_is_cloud
  community.general.pkgng:
    name:
      - sysutils/smartmontools
    state: absent

- name: Install base packages (common)
  community.general.pkgng:
    name:
      - archivers/zip
      - devel/bsddialog
      - devel/git
      - editors/bvi
      - editors/nano
      - editors/vim
      - ftp/curl
      - ftp/lftp
      - misc/buffer
      - misc/gnu-watch
      - misc/inplace
      - misc/mbuffer
      - misc/mc
      - net/croc
      - net/py-netaddr
      - net/rsync
      - net/socat
      - security/ca_root_nss
      - security/gnupg
      - shells/bash
      - shells/zsh
      - sysutils/ansible
      - sysutils/clone
      - sysutils/cpdup
      - sysutils/direnv
      - sysutils/filemon
      - sysutils/htop
      - sysutils/ncdu
      - sysutils/pv
      - sysutils/renameutils
      - sysutils/runit
      - sysutils/smenu
      - sysutils/spiped
      - sysutils/tmux
      - sysutils/ts
      - textproc/align
      - textproc/fzf
      - textproc/jq
      - textproc/the_silver_searcher
      - textproc/yq
    state: present
