---
- name: Install packages
  community.general.pkgng:
    name:
      - sysutils/runit
    state: present

- name: Create /var/service
  file:
    path: /var/service
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: Create /var/db/runit
  file:
    path: /var/db/runit
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: Check if /usr/local/etc/sv exists
  stat:
    path: /usr/local/etc/sv
  register: stat_usr_local_etc_sv

- name: Migrate /usr/local/etc/sv
  when: (stat_usr_local_etc_sv.stat.isdir is defined) and (stat_usr_local_etc_sv.stat.isdir)
  shell:
    cmd: |
      set -e -u -o pipefail

      for _file in /usr/local/etc/sv/*(N); do
          sv stop ${_file} || :
          mv -v ${_file} /var/db/runit/
      done

      rmdir /usr/local/etc/sv/
    executable: /usr/local/bin/zsh

- name: Enable service
  service:
    name: runsvdir
    enabled: true
    state: started
  notify:
    - reformat_rc_conf
