---
- name: Install sysctl.conf
  when: is_host_install
  copy:
    src: ../ansible/sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: wheel
    mode: "0644"
  notify:
    - restart_sysctl

- name: Check if /etc/sysctl.conf.local exists
  when: is_host_install
  stat:
    path: /etc/sysctl.conf.local
  register: stat_sysctl_conf_local

- name: Touch /etc/sysctl.conf.local
  when: is_host_install and not stat_sysctl_conf_local.stat.exists
  file:
    path: /etc/sysctl.conf.local
    state: touch
    mode: "0644"
