KERNCONF=		BSDKIT
BATCH=			yes
DISABLE_LICENSES=	yes
SU_CMD?=		/usr/local/bin/sudo -E sh -c
SENDMAIL_MC=		freebsd.mc
SENDMAIL_SUBMIT_MC=	freebsd.submit.mc
DEV_WARNING_WAIT=	1
USE_PACKAGE_DEPENDS=	yes
