#!/bin/sh

# 8f1c5926-23b8-4389-aafe-9fb5ac30ea44

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/*)"
fi

: ${DAPHNE_USER:="nobody"}
: ${DAPHNE_PATH:="/tmp"}
: ${DAPHNE_ARGS=""}
: ${DAPHNE_APP:="module.asgi:application"}
: ${DAPHNE_VENV:="${DAPHNE_PATH}/.venv"}
: ${DAPHNE_PYTHON:="python3"}
: ${DAPHNE_PYTHON_FLAGS=""}

cd ${DAPHNE_PATH}

. ${DAPHNE_VENV}/bin/activate

if [ "$(id -u)" = "0" ]; then
    CHPST_COMMAND="chpst -u ${DAPHNE_USER} ${CHPST_ARGS}"
fi

exec env -S "${ENVRC}" ${CHPST_COMMAND} ${DAPHNE_PYTHON} ${DAPHNE_PYTHON_FLAGS} -m daphne ${DAPHNE_ARGS} ${DAPHNE_APP}
