---
- name: pwd_mkdb
  command:
    cmd: pwd_mkdb -p /etc/master.passwd

- name: restart_syslogd
  service:
    name: syslogd
    state: restarted

- name: restart_cron
  service:
    name: cron
    state: restarted

- name: restart_sshd
  service:
    name: sshd
    state: restarted

- name: restart_ntpd
  service:
    name: ntpd
    state: restarted

- name: restart_netif
  service:
    name: netif
    state: restarted

- name: restart_routing
  service:
    name: routing
    state: restarted

- name: restart_sysctl
  service:
    name: sysctl
    state: restarted

- name: restart_hostname
  service:
    name: hostname
    state: restarted

- name: restart_postgresql
  service:
    name: postgresql
    state: restarted

- name: restart_caddy
  service:
    name: caddy
    state: restarted

- name: restart_fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart_monit
  service:
    name: monit
    state: restarted

- name: reload_monit
  shell:
    cmd: monit reload

- name: reformat_rc_conf
  shell:
    cmd: |
      set -e -u -o pipefail
      _rc_conf=$(mktemp /tmp/XXXXXX)
      sysrc -a -e > ${_rc_conf}
      cat ${_rc_conf} > /etc/rc.conf
      rm -f ${_rc_conf}

- name: reformat_loader_conf_local
  shell:
    cmd: |
      set -e -u -o pipefail
      _loader_conf_local=$(mktemp /tmp/XXXXXX)
      sed '/^$/d' /boot/loader.conf.local | sort > ${_loader_conf_local}
      cat ${_loader_conf_local} > /boot/loader.conf.local
      rm -f ${_loader_conf_local}
