---
- name: pwd_mkdb
  command:
    cmd: pwd_mkdb -p /etc/master.passwd

- name: restart_syslogd
  service:
    name: syslogd
    state: restarted

- name: restart_cron
  service:
    name: cron
    state: restarted

- name: restart_sshd
  service:
    name: sshd
    state: restarted

- name: restart_netif
  service:
    name: netif
    state: restarted

- name: restart_routing
  service:
    name: routing
    state: restarted

- name: reformat_rc_conf
  shell:
    cmd: |
      set -e -u -o pipefail
      _rc_conf=$(mktemp /tmp/XXXXXX)
      sysrc -a -e > ${_rc_conf}
      cat ${_rc_conf} > /etc/rc.conf
      rm -f ${_rc_conf}

- name: reformat_loader_conf_local
  shell:
    cmd: |
      set -e -u -o pipefail
      _loader_conf_local=$(mktemp /tmp/XXXXXX)
      cat /boot/loader.conf.local | grep -v '^$' | sort > ${_loader_conf_local}
      cat ${_loader_conf_local} > /boot/loader.conf.local
      rm -f ${_loader_conf_local}
