---
- name: pwd_mkdb
  command:
    cmd: pwd_mkdb -p /etc/master.passwd

- name: restart_syslogd
  service:
    name: syslogd
    state: restarted

- name: restart_cron
  service:
    name: cron
    state: restarted

- name: restart_sshd
  service:
    name: sshd
    state: restarted

- name: restart_netif
  service:
    name: netif
    state: restarted

- name: restart_routing
  service:
    name: routing
    state: restarted

- name: reformat_rc_conf
  shell:
    cmd: |
      set -e -u -o pipefail
      sysrc -a -e > /etc/.rc.conf
      cat /etc/.rc.conf > /etc/rc.conf
      rm -f /etc/.rc.conf
