---
- name: Add Nomad group
  group:
    name: nomad
    gid: "{{ nomad_user_gid }}"
    state: present

- name: Add Nomad user
  user:
    name: nomad
    uid: "{{ nomad_user_uid }}"
    group: nomad
    home: /var/db/nomad
    shell: /bin/sh
    comment: "Nomad Daemon"
    state: present

- name: Create data directory for Nomad
  file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: nomad
    group: nomad
  with_items:
    - /var/db/nomad

- name: Create /etc/rc.conf.d/nomad
  copy:
    dest: /etc/rc.conf.d/nomad
    content: |
      nomad_dir=/var/db/nomad
    owner: root
    group: wheel
    mode: "0644"
