---
- name: Set 'UseDNS no' in /etc/ssh/sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: UseDNS no
    regexp: ^UseDNS
    insertafter: EOF
# notify: restart_sshd

- name: Set 'PermitRootLogin without-password' in /etc/ssh/sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: PermitRootLogin without-password
    regexp: ^PermitRootLogin
    insertafter: EOF
# notify: restart_sshd

- name: "Create ssh directory for root"
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: "Create ssh identity for root"
  community.crypto.openssh_keypair:
    path: /root/.ssh/id_ed25519
    comment: root@{{ ansible_hostname }}
    type: ed25519
    owner: root
    group: wheel

- name: Set authorized_key
  when: bsdkit_ssh_public_key | length > 0
  ansible.posix.authorized_key:
    user: root
    key: "{{ bsdkit_ssh_public_key }}"
