---
- name: Create /usr/local/etc/syslog.d/
  file:
    path: /usr/local/etc/syslog.d/
    state: directory
    owner: root
    group: wheel
    mode: "0755"

- name: Remove obsolete syslog files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/etc/syslog.d/console.conf
  notify: restart_syslogd

- name: Install syslog.d files
  copy:
    src: "{{ item }}"
    dest: /usr/local/etc/syslog.d/
    owner: root
    group: wheel
    mode: "0644"
  with_fileglob:
    - ../ansible/syslog.d/*.conf
  notify: restart_syslogd

- name: Touch log files
  file:
    path: /var/log/{{ item }}
    state: touch
    mode: "0600"
  changed_when: false
  loop:
    - console.log

- name: Cleanup of /etc/syslog.conf
  replace:
    path: /etc/syslog.conf
    regexp: (manpage\.)#+$
    replace: \1
  notify: restart_syslogd

- name: Disable '/dev/console' target in /etc/syslog.conf
  replace:
    path: /etc/syslog.conf
    regexp: ^([^#].*/dev/console$)
    replace: "#\\1"
  notify: restart_syslogd
