---
- name: Install monit package
  community.general.pkgng:
    name: sysutils/monit
    state: present

- name: Create /usr/local/etc/monit.d
  file:
    path: /usr/local/etc/monit.d
    state: directory
    owner: root
    group: wheel
    mode: "0700"

- name: Create /usr/local/etc/bsdkit-monit.d
  file:
    path: /usr/local/etc/bsdkit-monit.d
    state: directory
    owner: root
    group: wheel
    mode: "0700"

- name: Create /var/monit
  file:
    path: /var/monit
    state: directory
    owner: root
    group: wheel
    mode: "0700"

- name: Check if /usr/local/etc/monitrc exists
  stat:
    path: /usr/local/etc/monitrc
  register: stat_monitrc

- name: Check if /usr/local/etc/monitrc contains marker
  command: grep -q "da7ec388-8086-439f-b9b5-0d0cdff0dd54" /usr/local/etc/monitrc
  register: grep_monitrc
  changed_when: false
  failed_when: grep_monitrc.rc == 2
  when: stat_monitrc.stat.exists

- name: Set manage_monitrc
  set_fact:
    manage_monitrc: "{{ stat_monitrc.stat.exists == false or (grep_monitrc is defined and grep_monitrc.rc == 0) }}"
  changed_when: false

- name: Create /usr/local/etc/monitrc
  template:
    src: monitrc.j2
    dest: /usr/local/etc/monitrc
    owner: root
    group: wheel
    mode: "0600"
  when: manage_monitrc == true
  notify:
    - reload_monit

- name: Create /usr/local/etc/bsdkit-monitrc (template)
  template:
    src: monitrc.j2
    dest: /usr/local/etc/bsdkit-monitrc
    owner: root
    group: wheel
    mode: "0600"
  when: manage_monitrc == false

- name: Remove /usr/local/etc/bsdkit-monitrc (template)
  file:
    path: /usr/local/etc/bsdkit-monitrc
    state: absent
  when: manage_monitrc == true

- name: Configure monit service
  include_tasks: monit-service.yml
  loop:
    - service: devd
      process: devd
      pid_file: /var/run/devd.pid
      host_only: true

    - service: smartd
      process: smartd
      pid_file: /var/run/smartd.pid
      host_only: true

    - service: apache24
      process: httpd
      pid_file: /var/run/httpd.pid
      host_only: false

    - service: caddy
      process: caddy
      pid_file: /var/run/caddy/caddy.pid
      host_only: false

    - service: charon
      process: charon
      pid_file: /var/run/charon.pid
      host_only: false

    - service: cron
      process: cron
      pid_file: /var/run/cron.pid
      host_only: false

    - service: fail2ban
      process: fail2ban
      pid_file: /var/run/fail2ban/fail2ban.pid
      host_only: false

    - service: gitlab_runner
      process: gitlab-runner
      pid_file: /var/run/gitlab_runner.pid
      host_only: false

    - service: inetd
      process: inetd
      pid_file: /var/run/inetd.pid
      host_only: false

    - service: mysql-server
      process: mysqld
      pid_file: /var/db/mysql/mysqld.pid
      host_only: false

    - service: named
      process: named
      pid_file: /var/run/named/pid
      host_only: false

    - service: nginx
      process: nginx
      pid_file: /var/run/nginx.pid
      host_only: false

    - service: ntpd
      process: ntpd
      pid_file: /var/db/ntp/ntpd.pid
      host_only: false

    - service: milter-opendkim
      process: opendkim
      pid_file: /var/run/milteropendkim/pid
      host_only: false

    - service: openvpn
      process: openvpn
      pid_file: /var/run/openvpn.pid
      host_only: false

    - service: php-fpm
      process: php-fpm
      pid_file: /var/run/php-fpm.pid
      host_only: false

    - service: postgresql
      process: postgresql
      matching: /usr/local/bin/postgres
      host_only: false

    - service: redis
      process: redis
      pid_file: /var/run/redis/redis.pid
      host_only: false

    - service: runsvdir
      process: runsvdir
      matching: /usr/local/sbin/runsvdir
      host_only: false

    - service: sshd
      process: sshd
      pid_file: /var/run/sshd.pid
      host_only: false

    - service: syslogd
      process: syslogd
      pid_file: /var/run/syslog.pid
      host_only: false

    - service: znapzend
      process: znapzend
      pid_file: /var/run/znapzend.pid
      host_only: false

- name: Enable monit service
  service:
    name: monit
    state: started
    enabled: true
