#!/bin/sh

# ID: 1f008a68-2398-11ed-aa96-b79b797c677d

set -o errexit -o nounset -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(grep -Ev '^\s*(#|$)' envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(grep -Ev '^\s*(#|$)' envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/* | grep -Ev '^\s*(#|$)')"
fi


: ${UWSGI_USER:="nobody"}
: ${UWSGI_PATH:="/tmp"}
: ${UWSGI_ARGS="--log-master --ini $(pwd)/uwsgi.ini"}
: ${UWSGI_VENV:="${UWSGI_PATH}/.venv"}
: ${UWSGI_PYTHON:="python3"}
: ${UWSGI_PYTHON_FLAGS=""}
: ${UWSGI_UV:=""}

eval export HOME=~${UWSGI_USER}

if [ -n "${PYENV_VERSION}" ]; then
    eval "$(pyenv init -)"
    pyenv shell ${PYENV_VERSION}
fi

cd ${UWSGI_PATH}

export OSTYPE=freebsd

PYTHON_PREFIX=""
if [ -n "${UWSGI_UV}" ]; then
    PYTHON_PREFIX="uv run "
else
    . ${UWSGI_VENV}/bin/activate
fi

if [ -n "${ENVRC}" ]; then
    exec env -S "${ENVRC}" chpst -u ${UWSGI_USER} ${CHPST_ARGS} ${PYTHON_PREFIX}${UWSGI_PYTHON} ${UWSGI_PYTHON_FLAGS} -m uwsgi ${UWSGI_ARGS}
else
    exec chpst -u ${UWSGI_USER} ${CHPST_ARGS} ${PYTHON_PREFIX}${UWSGI_PYTHON} ${UWSGI_PYTHON_FLAGS} -m uwsgi ${UWSGI_ARGS}
fi

# For logs: "--log-master"
