#!/bin/sh

# 1f008a68-2398-11ed-aa96-b79b797c677d

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . ./config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(grep -v '^\s*#' envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(grep -v '^\s*#' envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/* | grep -v '^\s*#')"
fi

ENV_ARGS=""
if [ -n "${ENVRC}" ]; then
    ENV_ARGS="-S \"${ENVRC}\""
fi

: ${UWSGI_USER:="nobody"}
: ${UWSGI_PATH:="/tmp"}
: ${UWSGI_ARGS="--log-master --ini $(pwd)/uwsgi.ini"}
: ${UWSGI_VENV:="${UWSGI_PATH}/.venv"}
: ${UWSGI_PYTHON:="python3"}
: ${UWSGI_PYTHON_FLAGS=""}
: ${UWSGI_UV:=""}

eval export HOME=~${UWSGI_USER}

if [ -n "${PYENV_VERSION}" ]; then
    eval "$(pyenv init -)"
    pyenv shell ${PYENV_VERSION}
fi

cd ${UWSGI_PATH}

export OSTYPE=freebsd

. ${UWSGI_VENV}/bin/activate

PYTHON_PREFIX=""
if [ -n "${UWSGI_UV}" ]; then
    PYTHON_PREFIX="uv run "
fi

exec env ${ENV_ARGS} chpst -u ${UWSGI_USER} ${CHPST_ARGS} ${PYTHON_PREFIX}${UWSGI_PYTHON} ${UWSGI_PYTHON_FLAGS} -m uwsgi ${UWSGI_ARGS}

# For logs: "--log-master"
