#!/bin/sh

# b45e463a-e8ec-4a5a-89ac-b764b1da00ef

set -e -u -o pipefail

exec 2>&1

[ -f config ] && . config

: ${CHPST_ARGS=""}

if [ -d env ]; then
    CHPST_ARGS="${CHPST_ARGS} -e ${PWD}/env"
fi

ENVRC=""

if [ -f envrc ]; then
    ENVRC="$(cat envrc)"
fi

if [ -f envrc.local ]; then
    ENVRC="${ENVRC} $(cat envrc.local)"
fi

if [ -d envrc.d ] && [ $(ls envrc.d | wc -l) -gt 0 ]; then
    ENVRC="${ENVRC} $(cat envrc.d/*)"
fi

: ${FASTSTREAM_USER:="nobody"}
: ${FASTSTREAM_PATH:="/tmp"}
: ${FASTSTREAM_ARGS=""}
: ${FASTSTREAM_APP:="app:app"}
: ${FASTSTREAM_VENV:="${FASTSTREAM_PATH}/.venv"}
: ${FASTSTREAM_PYTHON:="python3"}
: ${FASTSTREAM_PYTHON_FLAGS=""}

cd ${FASTSTREAM_PATH}

. ${FASTSTREAM_VENV}/bin/activate

if [ "$(id -u)" = "0" ]; then
    CHPST_COMMAND="chpst -u ${FASTSTREAM_USER} ${CHPST_ARGS}"
fi

exec env -S "${ENVRC}" ${CHPST_COMMAND} ${FASTSTREAM_PYTHON} ${FASTSTREAM_PYTHON_FLAGS} -m faststream ${FASTSTREAM_ARGS} ${FASTSTREAM_APP}
