---
- name: "Clean package cache"
  command:
    cmd: pkg clean -a -y
  changed_when: false
  failed_when: false

- name: "Remove ansible directory"
  file:
    path: /root/.ansible
    state: absent
  changed_when: false

- name: "Remove authorized_key"
  when: bsdkit_ssh_public_key | length > 0
  ansible.posix.authorized_key:
    user: root
    key: "{{ lookup('file', '../ansible/bsdkit.pub') }}"
    state: absent
